window.THEMODS_DATA = window.THEMODS_DATA || {};

window.THEMODS_DATA.age = [
  {"label":"AB","words":["ABATAGE", "ABATTAGE", "ABLOCAGE", "ABORDAGE", "ABOUTAGE", "ABREUVAGE"]},
  {"label":"AC","words":["ACCOLAGE", "ACCONAGE", "ACCORAGE", "ACCORDAGE", "ACCOSTAGE", "ACCOUVAGE", "ACHEVAGE", "ACIDAGE", "ACIÉRAGE", "ACONAGE"]},
  {"label":"AD","words":["ADAGE", "ADRESSAGE"]},
  {"label":"AE","words":["AÉRAGE"]},
  {"label":"AF","words":["AFFAITAGE", "AFFENAGE", "AFFERMAGE", "AFFICHAGE", "AFFILAGE", "AFFINAGE", "AFFLOUAGE", "AFFÛTAGE"]},
  {"label":"AG","words":["ÂGÉ", "AGIOTAGE", "AGNELAGE", "AGRAFAGE", "AGRAINAGE", "AGRÉAGE", "AGUICHAGE", "AGUILLAGE"]},
  {"label":"AI","words":["AIGAGE", "AIGUAGE", "AIGUISAGE"]},
  {"label":"AJ","words":["AJUSTAGE", "AJUTAGE"]},
  {"label":"AL","words":["ALÉSAGE", "ALEVINAGE", "ALLIAGE", "ALLUMAGE", "ALPAGE", "ALPHAPAGE", "ALUMINAGE", "ALUNAGE"]},
  {"label":"AM","words":["AMARINAGE", "AMARRAGE", "AMORÇAGE", "AMPÉRAGE"]},
  {"label":"AN","words":["ANCRAGE", "ANDAINAGE", "ANTIÂGE"]},
  {"label":"AP","words":["APIQUAGE", "APPAIRAGE", "APPLICAGE", "APPONTAGE", "APPRÊTAGE"]},
  {"label":"AR","words":["ARBITRAGE", "ARCHIVAGE", "ARÉAGE", "ARÉOPAGE", "ARGENTAGE", "ARPENTAGE", "ARRACHAGE", "ARRÊTAGE", "ARRIMAGE", "ARRIVAGE", "ARROSAGE"]},
  {"label":"AS","words":["ASSURAGE", "ASTIQUAGE"]},
  {"label":"AT","words":["ATTELAGE", "ATTERRAGE", "ATTRAPAGE"]},
  {"label":"AU","words":["AUBAGE", "AUNAGE"]},
  {"label":"AV","words":["AVINAGE", "AVIVAGE"]},
  {"label":"AZ","words":["AZURAGE"]},
  {"label":"BAB","words":["BABILLAGE"]},
  {"label":"BAC","words":["BÂCHAGE", "BACHOTAGE", "BACKSTAGE", "BÂCLAGE"]},
  {"label":"BAD","words":["BADINAGE"]},
  {"label":"BAG","words":["BAGAGE", "BAGUAGE"]},
  {"label":"BAH","words":["BAHUTAGE"]},
  {"label":"BAI","words":["BAILLIAGE"]},
  {"label":"BAL","words":["BALAYAGE", "BALEINAGE", "BALISAGE", "BALIVAGE", "BALLOTAGE"]},
  {"label":"BAN","words":["BANCHAGE", "BANDAGE"]},
  {"label":"BAR","words":["BARATTAGE", "BARBOTAGE", "BARDAGE", "BARIOLAGE", "BARONNAGE", "BARRAGE"]},
  {"label":"BAS","words":["BASSINAGE"]},
  {"label":"BAT","words":["BATELAGE", "BATILLAGE", "BÂTONNAGE", "BATTAGE"]},
  {"label":"BAV","words":["BAVARDAGE"]},
  {"label":"BE","words":["BÊCHAGE", "BÉGUINAGE", "BÉTONNAGE", "BEURRAGE"]},
  {"label":"BI","words":["BIDONNAGE", "BIFFAGE", "BIGORNAGE", "BILLAGE", "BILLETAGE", "BINAGE", "BITUMAGE", "BIVOLTAGE", "BIZUTAGE"]},
  {"label":"BL","words":["BLÂMAGE", "BLINDAGE", "BLOCAGE", "BLOGAGE", "BLUTAGE"]},
  {"label":"BOB","words":["BOBINAGE"]},
  {"label":"BOC","words":["BOCAGE", "BOCARDAGE"]},
  {"label":"BOI","words":["BOISAGE", "BOÎTAGE"]},
  {"label":"BOM","words":["BOMBAGE"]},
  {"label":"BON","words":["BONDAGE"]},
  {"label":"BOR","words":["BORDAGE", "BORNAGE"]},
  {"label":"BOS","words":["BOSSAGE", "BOSSELAGE"]},
  {"label":"BOT","words":["BOTTELAGE"]},
  {"label":"BOU","words":["BOUCAGE", "BOUCANAGE", "BOUCHAGE", "BOUCLAGE", "BOUDINAGE", "BOULAGE", "BOULETAGE", "BOURRAGE", "BOUTURAGE", "BOUVETAGE"]},
  {"label":"BRA","words":["BRADAGE", "BRAISAGE", "BRANCHAGE", "BRAQUAGE", "BRASAGE", "BRASSAGE"]},
  {"label":"BRE","words":["BREFFAGE", "BRÊLAGE", "BRELLAGE", "BREUVAGE", "BREVETAGE"]},
  {"label":"BRI","words":["BRICOLAGE", "BRIDAGE"]},
  {"label":"BRO","words":["BROCHAGE", "BRONZAGE", "BROSSAGE", "BROUTAGE", "BROYAGE"]},
  {"label":"BRU","words":["BRUISSAGE", "BRUITAGE", "BRÛLAGE"]},
  {"label":"BU","words":["BUFFLAGE", "BURINAGE", "BUTINAGE", "BUTTAGE"]},
  {"label":"CAB","words":["CÂBLAGE", "CABOTAGE", "CABRAGE"]},
  {"label":"CAC","words":["CACHETAGE"]},
  {"label":"CAD","words":["CADMIAGE", "CADRAGE"]},
  {"label":"CAF","words":["CAFARDAGE"]},
  {"label":"CAG","words":["CAGE"]},
  {"label":"CAI","words":["CAILLAGE"]},
  {"label":"CAL","words":["CALAGE", "CALFATAGE", "CALIBRAGE", "CALMAGE", "CALQUAGE"]},
  {"label":"CAM","words":["CAMBRAGE"]},
  {"label":"CAN","words":["CANARDAGE", "CANETAGE", "CANNAGE", "CANNETAGE", "CANONNAGE", "CANOTAGE"]},
  {"label":"CAP","words":["CAPELAGE", "CAPOTAGE", "CAPSAGE", "CAPSULAGE", "CAPTAGE"]},
  {"label":"CAQ","words":["CAQUAGE", "CAQUETAGE"]},
  {"label":"CAR","words":["CARAFAGE", "CARDAGE", "CARÉNAGE", "CARNAGE", "CAROTTAGE", "CARRELAGE", "CARROYAGE", "CARTILAGE"]},
  {"label":"CAS","words":["CASSAGE"]},
  {"label":"CAT","words":["CATINAGE", "CATISSAGE"]},
  {"label":"CAV","words":["CAVAGE"]},
  {"label":"CE","words":["CENTILAGE", "CENTRAGE", "CÉPAGE", "CERCLAGE", "CERNAGE"]},
  {"label":"CHA","words":["CHAÎNAGE", "CHALUTAGE", "CHAMBRAGE", "CHANTAGE", "CHARRIAGE", "CHARRUAGE", "CHASSAGE", "CHAUFFAGE", "CHAULAGE", "CHAUMAGE", "CHAUSSAGE", "CHAVIRAGE"]},
  {"label":"CHE","words":["CHEMISAGE", "CHEVAGE"]},
  {"label":"CHI","words":["CHIALAGE", "CHIFFRAGE", "CHINAGE", "CHIPAGE", "CHIPOTAGE"]},
  {"label":"CHL","words":["CHLORAGE"]},
  {"label":"CHO","words":["CHÔMAGE"]},
  {"label":"CHR","words":["CHROMAGE"]},
  {"label":"CI","words":["CIBLAGE", "CIMENTAGE", "CINÉPHAGE", "CINGLAGE", "CINTRAGE", "CIRAGE", "CISELAGE"]},
  {"label":"CLA","words":["CLABOTAGE", "CLAIRÇAGE", "CLAMPAGE", "CLAPOTAGE", "CLAQUAGE", "CLASSAGE", "CLAVAGE", "CLAVETAGE"]},
  {"label":"CLI","words":["CLICHAGE", "CLIPSAGE", "CLISSAGE", "CLIVAGE"]},
  {"label":"CLO","words":["CLONAGE", "CLOQUAGE", "CLOUAGE", "CLOUTAGE"]},
  {"label":"COB","words":["COBALTAGE"]},
  {"label":"COC","words":["COCONNAGE", "COCUAGE", "COCUFIAGE"]},
  {"label":"COD","words":["CODAGE"]},
  {"label":"COF","words":["COFFRAGE"]},
  {"label":"COI","words":["COIFFAGE", "COINÇAGE"]},
  {"label":"COK","words":["COKAGE"]},
  {"label":"COL","words":["COLISAGE", "COLLAGE", "COLMATAGE", "COLOMBAGE", "COLONAGE", "COLORAGE", "COLORIAGE", "COLTINAGE"]},
  {"label":"COM","words":["COMMÉRAGE", "COMPÉRAGE", "COMPTAGE"]},
  {"label":"CON","words":["CONCHAGE", "CONTAGE", "CONVOYAGE"]},
  {"label":"COP","words":["COPIAGE", "COPINAGE", "COPSAGE"]},
  {"label":"COR","words":["CORDAGE", "CORNAGE", "CORROYAGE", "CORSAGE"]},
  {"label":"COT","words":["COTTAGE"]},
  {"label":"COU","words":["COUCHAGE", "COUDAGE", "COULAGE", "COUPAGE", "COUPLAGE", "COURAGE", "COURBAGE", "COURTAGE", "COUSINAGE"]},
  {"label":"CR","words":["CRABOTAGE", "CRANTAGE", "CRAQUAGE", "CRÉMAGE", "CRÉNAGE", "CRÉNELAGE", "CRÊPAGE", "CREUSAGE", "CRIBLAGE", "CROÛTAGE", "CRYPTAGE"]},
  {"label":"CU","words":["CUBAGE", "CUEILLAGE", "CUISSAGE /", "CUIVRAGE", "CULBUTAGE", "CULOTAGE", "CULOTTAGE", "CURAGE", "CURETAGE", "CURETTAGE", "CUVAGE", "CUVELAGE"]},
  {"label":"DA","words":["DALLAGE", "DAMAGE", "DATAGE", "DAVANTAGE"]},
  {"label":"DEB","words":["DÉBÂCHAGE", "DÉBALLAGE", "DÉBARDAGE", "DÉBINAGE", "DÉBITAGE", "DÉBLAYAGE", "DÉBLOCAGE", "DÉBOGAGE", "DÉBOISAGE", "DÉBOÎTAGE", "DÉBOSSAGE", "DÉBRASAGE", "DÉBRAYAGE", "DÉBRIDAGE"]},
  {"label":"DEC","words":["DÉCADRAGE", "DÉCALAGE", "DÉCANTAGE", "DÉCAPAGE", "DÉCHIRAGE", "DÉCHOCAGE", "DÉCILAGE", "DÉCLOUAGE", "DÉCOCHAGE", "DÉCODAGE", "DÉCOLLAGE", "DÉCONNAGE", "DÉCORNAGE", "DÉCOUPAGE", "DÉCRÊPAGE", "DÉCRUAGE", "DÉCRUSAGE", "DÉCUVAGE"]},
  {"label":"DED","words":["DÉDORAGE"]},
  {"label":"DEF","words":["DÉFAÇAGE", "DÉFERLAGE", "DÉFERRAGE", "DÉFIBRAGE", "DÉFILAGE", "DÉFLOCAGE", "DÉFONÇAGE", "DÉFRISAGE"]},
  {"label":"DEG","words":["DÉGAZAGE", "DÉGIVRAGE", "DÉGLAÇAGE", "DÉGOMMAGE", "DÉGRAFAGE"]},
  {"label":"DEH","words":["DÉHALAGE"]},
  {"label":"DEL","words":["DÉLAINAGE", "DÉLAITAGE", "DÉLAVAGE", "DÉLAYAGE", "DÉLESTAGE", "DÉLIGNAGE", "DÉLISSAGE", "DÉLITAGE", "DÉLUTAGE"]},
  {"label":"DEM","words":["DÉMARCAGE", "DÉMARIAGE", "DÉMARRAGE", "DÉMÂTAGE", "DÉMÉCHAGE", "DÉMÊLAGE", "DÉMINAGE", "DÉMONTAGE", "DÉMOULAGE"]},
  {"label":"DEN","words":["DÉNICHAGE", "DÉNOYAGE"]},
  {"label":"DEP","words":["DÉPANNAGE", "DÉPAVAGE", "DÉPEÇAGE", "DÉPENDAGE", "DÉPHASAGE", "DÉPICAGE", "DÉPILAGE", "DÉPIQUAGE", "DÉPISTAGE", "DÉPLIAGE", "DÉPOTAGE", "DÉPULPAGE"]},
  {"label":"DER","words":["DÉRAPAGE", "DÉRAYAGE", "DÉRIDAGE", "DÉROCHAGE", "DÉROCTAGE", "DÉROULAGE", "DÉROUTAGE"]},
  {"label":"DES","words":["DÉSAÉRAGE", "DÉSOSSAGE", "DESSALAGE", "DESSÉVAGE"]},
  {"label":"DET","words":["DÉTACHAGE", "DÉTELAGE", "DÉTERRAGE", "DÉTOURAGE"]},
  {"label":"DEV","words":["DÉVIDAGE", "DÉVISSAGE", "DÉVOLTAGE"]},
  {"label":"DEZ","words":["DÉZINGAGE", "DÉZONAGE"]},
  {"label":"DO","words":["DODINAGE", "DOLAGE", "DOMMAGE", "DOMPTAGE", "DOPAGE", "DORAGE", "DOSAGE", "DOUBLAGE"]},
  {"label":"DR","words":["DRAGAGE", "DRAINAGE", "DRAYAGE", "DRESSAGE", "DROPAGE", "DROPPAGE"]},
  {"label":"DU","words":["DUITAGE", "DUPLEXAGE"]},
  {"label":"EB","words":["ÉBARBAGE", "ÉBAUCHAGE", "ÉBAVURAGE", "ÉBORGNAGE", "ÉBOUAGE", "ÉBOUTAGE"]},
  {"label":"ECA","words":["ÉCAILLAGE", "ÉCANGAGE"]},
  {"label":"ECH","words":["ÉCHARNAGE", "ÉCHAUDAGE", "ÉCHOUAGE"]},
  {"label":"ECI","words":["ÉCIMAGE"]},
  {"label":"ECL","words":["ÉCLAIRAGE", "ÉCLISSAGE", "ÉCLUSAGE"]},
  {"label":"ECO","words":["ÉCOBUAGE", "ÉCOLAGE", "ÉCOPAGE", "ÉCORÇAGE", "ÉCORCHAGE", "ÉCOSSAGE", "ÉCÔTAGE"]},
  {"label":"ECR","words":["ÉCRANTAGE", "ÉCRÉMAGE", "ÉCRÊTAGE", "ÉCROÛTAGE"]},
  {"label":"ECU","words":["ÉCUMAGE", "ÉCURAGE"]},
  {"label":"EF","words":["EFFAÇAGE", "EFFANAGE", "EFFILAGE"]},
  {"label":"EG","words":["ÉGOUTTAGE", "ÉGRAINAGE", "ÉGRAPPAGE", "ÉGRENAGE", "ÉGRISAGE", "ÉGRUGEAGE"]},
  {"label":"EJ","words":["ÉJOINTAGE"]},
  {"label":"EL","words":["ÉLAGAGE", "ÉLEVAGE", "ÉLINGAGE"]},
  {"label":"EMA","words":["ÉMAILLAGE"]},
  {"label":"EMB","words":["EMBALLAGE", "EMBÂTAGE", "EMBATTAGE", "EMBLAVAGE", "EMBOÎTAGE", "EMBOSSAGE", "EMBOUAGE", "EMBRAYAGE", "EMBUVAGE"]},
  {"label":"EMI","words":["ÉMINÇAGE"]},
  {"label":"EMO","words":["ÉMONDAGE", "ÉMOTTAGE", "ÉMOULAGE", "ÉMOUSSAGE"]},
  {"label":"EMP","words":["EMPALMAGE", "EMPANNAGE", "EMPÊNAGE", "EMPENNAGE", "EMPESAGE", "EMPILAGE", "EMPOTAGE"]},
  {"label":"ENA","words":["ÉNALLAGE"]},
  {"label":"ENC","words":["ENCARTAGE", "ENCAVAGE", "ENCLOUAGE", "ENCOCHAGE", "ENCODAGE", "ENCOLLAGE", "ENCORDAGE", "ENCRAGE", "ENCULAGE", "ENCUVAGE"]},
  {"label":"END","words":["ENDIGAGE", "ENDUISAGE"]},
  {"label":"ENF","words":["ENFICHAGE", "ENFILAGE", "ENFUMAGE", "ENFÛTAGE"]},
  {"label":"ENG","words":["ENGERBAGE", "ENGLUAGE", "ENGOBAGE", "ENGOMMAGE", "ENGRENAGE"]},
  {"label":"ENL","words":["ENLEVAGE"]},
  {"label":"ENN","words":["ENNOYAGE"]},
  {"label":"ENO","words":["ÉNOUAGE"]},
  {"label":"ENR","words":["ENRAYAGE", "ENROBAGE", "ENROULAGE"]},
  {"label":"ENS","words":["ENSACHAGE", "ENSILAGE", "ENSIMAGE"]},
  {"label":"ENT","words":["ENTARTAGE", "ENTERRAGE", "ENTOILAGE", "ENTÔLAGE", "ENTONNAGE", "ENTOURAGE", "ENTUBAGE"]},
  {"label":"ENV","words":["ENVIDAGE"]},
  {"label":"EP","words":["ÉPAILLAGE", "ÉPAMPRAGE", "ÉPANDAGE", "ÉPÉPINAGE", "ÉPIAGE", "ÉPIERRAGE", "ÉPILAGE", "ÉPINÇAGE", "ÉPINGLAGE", "ÉPISSAGE", "ÉPLUCHAGE", "ÉPOINTAGE", "ÉPONGEAGE", "ÉPURAGE"]},
  {"label":"EQ","words":["ÉQUERRAGE", "ÉQUEUTAGE", "ÉQUIPAGE"]},
  {"label":"ER","words":["ÉREINTAGE", "ERGOTAGE", "ERMITAGE"]},
  {"label":"ES","words":["ESSAIMAGE", "ESSANVAGE", "ESSARTAGE", "ESSAYAGE", "ESSORAGE", "ESSUYAGE", "ESTAMPAGE", "ESTIVAGE", "ESTOMPAGE"]},
  {"label":"ET","words":["ÉTAMAGE", "ÉTAMPAGE", "ÉTAYAGE", "ÉTENDAGE", "ÉTÊTAGE", "ÉTIAGE", "ÉTIRAGE", "ÉTOUFFAGE", "ÉTOUPAGE", "ÉTRIPAGE", "ÉTUVAGE"]},
  {"label":"EU","words":["EUBAGE"]},
  {"label":"EV","words":["ÉVEINAGE", "ÉVIDAGE", "ÉVITAGE"]},
  {"label":"EX","words":["EXPRIMAGE"]},
  {"label":"FAC","words":["FAÇONNAGE", "FACTAGE", "FACTORAGE"]},
  {"label":"FAG","words":["FAGOTAGE"]},
  {"label":"FAI","words":["FAÏENÇAGE", "FAÎTAGE"]},
  {"label":"FAL","words":["FALUNAGE"]},
  {"label":"FAN","words":["FANAGE"]},
  {"label":"FAR","words":["FARDAGE", "FARDELAGE", "FARINAGE", "FARTAGE"]},
  {"label":"FAS","words":["FASCINAGE"]},
  {"label":"FAU","words":["FAUCHAGE", "FAUFILAGE"]},
  {"label":"FAY","words":["FAYOTAGE"]},
  {"label":"FE","words":["FENDAGE", "FENÊTRAGE", "FERLAGE", "FERMAGE", "FERRAGE", "FEUILLAGÉ", "FEUTRAGE"]},
  {"label":"FI","words":["FICELAGE", "FICHAGE", "FIGNOLAGE", "FILAGE", "FILETAGE", "FILMAGE", "FILOUTAGE", "FILTRAGE", "FINAGE", "FINISSAGE", "FIXAGE"]},
  {"label":"FL","words":["FLAMBAGE", "FLÂNAGE", "FLASHAGE", "FLÉCHAGE", "FLEURAGE", "FLICAGE", "FLOCAGE", "FLOCKAGE", "FLOTTAGE", "FLOUTAGE", "FLUAGE", "FLUXAGE"]},
  {"label":"FOL","words":["FOLIOTAGE"]},
  {"label":"FON","words":["FONÇAGE"]},
  {"label":"FOR","words":["FORAGE", "FORÇAGE", "FORESTAGE", "FORETAGE", "FORGEAGE", "FORMAGE", "FORMATAGE", "FORMOLAGE", "FORTAGE"]},
  {"label":"FOS","words":["FOSSOYAGE"]},
  {"label":"FOU","words":["FOUAGE", "FOUILLAGE", "FOUISSAGE", "FOULAGE", "FOUTAGE"]},
  {"label":"FR","words":["FRAISAGE", "FRAPPAGE", "FRAYAGE", "FRÉGATAGE", "FREINAGE", "FRELATAGE", "FRETTAGE", "FRICOTAGE", "FRISAGE", "FRITTAGE", "FROMAGÉ", "FROTTAGE", "FRUITAGE"]},
  {"label":"FU","words":["FUMAGE", "FURETAGE", "FUSELAGE"]},
  {"label":"GA","words":["GABARIAGE", "GÂCHAGE", "GAGNAGE", "GAINAGE", "GALANDAGE", "GALETAGE", "GARAGE", "GARANÇAGE", "GARROTAGE", "GAUFRAGE", "GAULAGE", "GAVAGE", "GAZAGE", "GAZONNAGE"]},
  {"label":"GE","words":["GEMMAGE", "GÉOPHAGE", "GERBAGE"]},
  {"label":"GI","words":["GÎTAGE", "GIVRAGE"]},
  {"label":"GL","words":["GLAÇAGE", "GLANAGE", "GLANDAGE", "GLISSAGE"]},
  {"label":"GO","words":["GOBAGE", "GOBETAGE", "GODAGE", "GOMMAGE", "GONDOLAGE", "GONFLAGE", "GOUGEAGE"]},
  {"label":"GRA","words":["GRAINAGE", "GRAISSAGE", "GRAMMAGE", "GRATTAGE", "GRAVAGE", "GRAVELAGE"]},
  {"label":"GRE","words":["GRÉAGE", "GRECQUAGE", "GREFFAGE", "GRENADAGE", "GRENAGE", "GRÉSAGE"]},
  {"label":"GRI","words":["GRICHAGE", "GRIFFAGE", "GRIMAGE", "GRIPPAGE"]},
  {"label":"GRO","words":["GROUPAGE"]},
  {"label":"GRU","words":["GRUTAGE"]},
  {"label":"GU","words":["GUIDAGE", "GUINDAGE", "GUIPAGE", "GUNITAGE"]},
  {"label":"GY","words":["GYPSAGE"]},
  {"label":"HA","words":["HABILLAGE", "HACHAGE", "HALAGE", "HALLAGE", "HAUBANAGE", "HAVAGE"]},
  {"label":"HE","words":["HERCHAGE", "HÉRITAGE", "HERMITAGE", "HERSAGE", "HERSCHAGE"]},
  {"label":"HI","words":["HISSAGE", "HIVERNAGE"]},
  {"label":"HO","words":["HOMMAGE", "HOUAGE", "HOURDAGE", "HOUSSAGE"]},
  {"label":"HU","words":["HUILAGE", "HUMAGE", "HUMECTAGE"]},
  {"label":"HY","words":["HYPALLAGE"]},
  {"label":"IL","words":["ÎLOTAGE"]},
  {"label":"IN","words":["INALPAGE", "INDEXAGE", "INERTAGE"]},
  {"label":"IX","words":["IXAGE"]},
  {"label":"JA","words":["JABLAGE", "JABOTAGE", "JAMBAGE", "JARDINAGE", "JAUGEAGE", "JAVELAGE"]},
  {"label":"JE","words":["JETAGE"]},
  {"label":"JO","words":["JOINTAGE", "JONGLAGE"]},
  {"label":"JU","words":["JUMELAGE"]},
  {"label":"LAB","words":["LABOURAGE"]},
  {"label":"LAC","words":["LAÇAGE", "LÂCHAGE"]},
  {"label":"LAG","words":["LAGUNAGE"]},
  {"label":"LAI","words":["LAINAGE", "LAITAGE"]},
  {"label":"LAM","words":["LAMAGE", "LAMANAGE", "LAMBINAGE", "LAMINAGE"]},
  {"label":"LAN","words":["LANÇAGE", "LANGAGE"]},
  {"label":"LAQ","words":["LAQUAGE"]},
  {"label":"LAR","words":["LARDAGE", "LARGAGE"]},
  {"label":"LAS","words":["LASURAGE"]},
  {"label":"LAT","words":["LATTAGE"]},
  {"label":"LAV","words":["LAVAGE"]},
  {"label":"LAY","words":["LAYAGE"]},
  {"label":"LE","words":["LÉCHAGE", "LESSIVAGE", "LESTAGE", "LETTRAGE", "LEVAGE", "LEVURAGE"]},
  {"label":"LI","words":["LIAGE", "LIBAGE", "LIGNAGE", "LIGOTAGE", "LIMAGE", "LIMOGEAGE", "LIMONAGE", "LINKAGE", "LISAGE", "LISERAGE", "LISSAGE", "LISTAGE", "LITAGE", "LITRAGE"]},
  {"label":"LO","words":["LOUAGE", "LOUPAGE", "LOUVOYAGE"]},
  {"label":"LU","words":["LUSTRAGE", "LUTAGE"]},
  {"label":"LY","words":["LYNCHAGE"]},
  {"label":"MAC","words":["MACLAGE", "MAÇONNAGE", "MACQUAGE", "MACULAGE"]},
  {"label":"MAG","words":["MAGE"]},
  {"label":"MAI","words":["MAILLAGE"]},
  {"label":"MAL","words":["MALAXAGE", "MALMENAGE", "MALTAGE"]},
  {"label":"MAN","words":["MANIAGE", "MANOQUAGE"]},
  {"label":"MAP","words":["MAPPAGE"]},
  {"label":"MAR","words":["MARAUDAGE", "MARCHÉAGE", "MARÉCAGE", "MAREYAGE", "MARIAGE", "MARINAGE", "MARMITAGE", "MARNAGE", "MARONAGE", "MARQUAGE", "MARTELAGE"]},
  {"label":"MAS","words":["MASQUAGE", "MASSAGE", "MASTICAGE"]},
  {"label":"MAT","words":["MATAGE", "MATERNAGE", "MATOSSAGE", "MATRIÇAGE"]},
  {"label":"MAZ","words":["MAZÉAGE", "MAZOUTAGE"]},
  {"label":"MEC","words":["MÉCHAGE"]},
  {"label":"MEG","words":["MÉGISSAGE", "MÉGOTAGE"]},
  {"label":"MEJ","words":["MÉJANAGE"]},
  {"label":"MEL","words":["MÉLIPHAGE", "MÉLOPHAGE"]},
  {"label":"MEM","words":["MÉMÉRAGE"]},
  {"label":"MEN","words":["MENOTTAGE", "MENUISAGE"]},
  {"label":"MER","words":["MERINGAGE"]},
  {"label":"MES","words":["MESSAGE", "MESURAGE", "MÉSUSAGE"]},
  {"label":"MET","words":["MÉTAYAGE", "MÉTISSAGE", "MÉTRAGE"]},
  {"label":"MEU","words":["MEULAGE"]},
  {"label":"MI","words":["MIJOTAGE", "MILLAGE", "MINAGE", "MINUTAGE", "MIRAGE", "MITAGE", "MIXAGE"]},
  {"label":"MO","words":["MODELAGE", "MOIRAGE", "MOISAGE", "MOLETAGE", "MONNAYAGE", "MONTAGE", "MORFILAGE", "MOUCHAGE", "MOUFLAGE", "MOUILLAGE", "MOULAGE", "MOULINAGE", "MOULURAGE", "MOUSSAGE"]},
  {"label":"MU","words":["MUCILAGE", "MURAGE", "MÛRISSAGE", "MUSELAGE", "MUTAGE"]},
  {"label":"MY","words":["MYCOPHAGE"]},
  {"label":"NA","words":["NAISSAGE", "NAPPAGE", "NATTAGE"]},
  {"label":"NE","words":["NERVURAGE", "NETTOYAGE"]},
  {"label":"NI","words":["NIAISAGE", "NICKELAGE", "NIELLAGE", "NIVELAGE"]},
  {"label":"NO","words":["NOMMAGE", "NOUAGE", "NOYAGE", "NOYAUTAGE"]},
  {"label":"NU","words":["NUAGE", "NURSAGE"]},
  {"label":"OE","words":["ŒSOPHAGE"]},
  {"label":"OR","words":["ORAGE", "ORNIÉRAGE"]},
  {"label":"OT","words":["OTAGE"]},
  {"label":"OU","words":["OUATAGE", "OUILLAGE", "OUTILLAGE"]},
  {"label":"PAC","words":["PACKAGE", "PACQUAGE"]},
  {"label":"PAI","words":["PAILLAGE", "PAIRAGE"]},
  {"label":"PAL","words":["PALISSAGE", "PALOTAGE"]},
  {"label":"PAN","words":["PANACHAGE", "PANSAGE"]},
  {"label":"PAP","words":["PAPOTAGE"]},
  {"label":"PAQ","words":["PAQUAGE", "PAQUETAGE"]},
  {"label":"PAR","words":["PARAGE", "PARCAGE", "PARÉAGE", "PARENTAGE", "PARFILAGE", "PARIAGE"]},
  {"label":"PAS","words":["PASSAGE", "PASSERAGE"]},
  {"label":"PAT","words":["PATENTAGE", "PATINAGE", "PÂTISSAGE", "PATRONAGE", "PÂTURAGE"]},
  {"label":"PAV","words":["PAVAGE"]},
  {"label":"PAY","words":["PAYSAGÉ"]},
  {"label":"PE","words":["PÉAGE", "PÉDALAGE", "PEIGNAGE", "PELAGE", "PELLETAGE", "PELOTAGE", "PELUCHAGE", "PENDAGE", "PENNAGE", "PERÇAGE", "PERCHAGE", "PERFORAGE", "PERLAGE", "PESAGE", "PÉTAGE"]},
  {"label":"PH","words":["PHAGE", "PHASAGE"]},
  {"label":"PIA","words":["PIANOTAGE"]},
  {"label":"PIC","words":["PICAGE", "PICOSSAGE", "PICOTAGE"]},
  {"label":"PIE","words":["PIÉGEAGE", "PIERRAGE"]},
  {"label":"PIL","words":["PILAGE", "PILLAGE", "PILONNAGE", "PILOTAGE"]},
  {"label":"PIN","words":["PINÇAGE"]},
  {"label":"PIO","words":["PIOCHAGE"]},
  {"label":"PIP","words":["PIPETAGE", "PIPETTAGE"]},
  {"label":"PIQ","words":["PIQUAGE", "PIQUETAGE"]},
  {"label":"PIR","words":["PIRATAGE"]},
  {"label":"PIS","words":["PISTAGE"]},
  {"label":"PIT","words":["PITONNAGE"]},
  {"label":"PL","words":["PLACAGE", "PLACOTAGE", "PLAGE", "PLANAGE", "PLANTAGE", "PLAQUAGE", "PLATELAGE", "PLATINAGE", "PLÂTRAGE", "PLEURAGE", "PLIAGE", "PLISSAGE", "PLOMBAGE", "PLOYAGE", "PLUMAGE"]},
  {"label":"POC","words":["POCHAGE"]},
  {"label":"POE","words":["POÊLAGE"]},
  {"label":"POI","words":["POINTAGE", "POIVRAGE"]},
  {"label":"POL","words":["POLISSAGE"]},
  {"label":"POM","words":["POMPAGE"]},
  {"label":"PON","words":["PONÇAGE", "PONTAGE"]},
  {"label":"POP","words":["POPULAGE"]},
  {"label":"POS","words":["POSAGE", "POSTAGE"]},
  {"label":"POT","words":["POTAGE"]},
  {"label":"POU","words":["POUDRAGE", "POULINAGE", "POUSSAGE", "POUTRAGE"]},
  {"label":"PR","words":["PRALINAGE", "PRÉLAVAGE", "PRÉRASAGE", "PRESSAGE", "PRIMAGE", "PROFILAGE"]},
  {"label":"PU","words":["PUÇAGE", "PUCELAGE", "PUDDLAGE", "PUISAGE", "PURINAGE"]},
  {"label":"QU","words":["QUEUTAGE"]},
  {"label":"RAB","words":["RABÂCHAGE", "RABATTAGE", "RABIOTAGE", "RABOTAGE", "RABOUTAGE"]},
  {"label":"RAC","words":["RACAGE", "RACINAGE", "RACLAGE", "RACOLAGE"]},
  {"label":"RAD","words":["RADOTAGE", "RADOUBAGE"]},
  {"label":"RAF","words":["RAFFINAGE", "RAFFÛTAGE"]},
  {"label":"RAG","words":["RAGAGE", "RAGRÉAGE"]},
  {"label":"RAI","words":["RAINURAGE"]},
  {"label":"RAL","words":["RALLUMAGE"]},
  {"label":"RAM","words":["RAMASSAGE", "RAMONAGE"]},
  {"label":"RAP","words":["RÂPAGE", "RAPIÉÇAGE"]},
  {"label":"RAS","words":["RASAGE"]},
  {"label":"RAT","words":["RATAGE", "RÂTELAGE", "RATINAGE", "RATISSAGE", "RATURAGE"]},
  {"label":"RAU","words":["RAUCHAGE"]},
  {"label":"RAV","words":["RAVAUDAGE", "RAVIVAGE"]},
  {"label":"RAY","words":["RAYAGE", "RAYONNAGE"]},
  {"label":"REA","words":["RÉALÉSAGE"]},
  {"label":"REC","words":["RECADRAGE", "RECALAGE", "RECÉPAGE", "RECETTAGE", "RECHAPAGE", "RECOLLAGE", "RECOPIAGE", "RECORDAGE", "RECOUPAGE", "RÉCURAGE", "RECYCLAGE"]},
  {"label":"REF","words":["REFORMAGE"]},
  {"label":"REG","words":["RÉGALAGE", "RÉGLAGE", "REGOMMAGE", "RÉGULAGE"]},
  {"label":"REL","words":["RELARGAGE", "RELAVAGE", "RELEVAGE", "RELIAGE", "RELOOKAGE"]},
  {"label":"REM","words":["REMARIAGE", "REMISAGE", "REMIXAGE", "REMONTAGE", "REMOULAGE", "REMPLAGE", "REMPOTAGE", "REMUAGE"]},
  {"label":"REN","words":["RENOMMAGE", "RENTRAGE", "RENVIDAGE"]},
  {"label":"REP","words":["REPASSAGE", "REPAVAGE", "REPÊCHAGE", "REPÉRAGE", "REPERÇAGE", "REPIQUAGE", "REPORTAGE", "REPRISAGE"]},
  {"label":"RER","words":["REROUTAGE"]},
  {"label":"RES","words":["RESSAYAGE", "RESSUAGE", "RESSUYAGE", "RESTYLAGE"]},
  {"label":"RET","words":["RÉTAMAGE", "RETAPAGE", "RETERÇAGE", "RETERSAGE", "RETIRAGE", "RETISSAGE", "RETOQUAGE", "RETORDAGE"]},
  {"label":"REV","words":["REVIRAGE", "REVISSAGE"]},
  {"label":"RH","words":["RHODIAGE"]},
  {"label":"RI","words":["RIBLAGE", "RIDAGE", "RIGOLAGE", "RINÇAGE", "RIPAGE", "RIVAGE", "RIVETAGE"]},
  {"label":"RO","words":["ROBAGE", "ROBELAGE", "ROCHAGE", "RODAGE", "ROGNAGE", "RÔLAGE", "ROSAGE", "RÔTISSAGE", "ROUAGE", "ROUISSAGE", "ROULAGE", "ROUTAGE"]},
  {"label":"RU","words":["RUSTICAGE"]},
  {"label":"SAB","words":["SABLAGE", "SABORDAGE", "SABOTAGE", "SABRAGE"]},
  {"label":"SAG","words":["SAGE"]},
  {"label":"SAL","words":["SALAGE", "SALINAGE"]},
  {"label":"SAN","words":["SANGLAGE"]},
  {"label":"SAP","words":["SAPINAGE"]},
  {"label":"SAR","words":["SARCLAGE"]},
  {"label":"SAS","words":["SASSAGE", "SASSENAGE"]},
  {"label":"SAT","words":["SATINAGE"]},
  {"label":"SAU","words":["SAUMURAGE", "SAUNAGE", "SAURAGE", "SAUTAGE", "SAUVAGE", "SAUVETAGE"]},
  {"label":"SAV","words":["SAVONNAGE"]},
  {"label":"SAX","words":["SAXIFRAGE"]},
  {"label":"SC","words":["SCANNAGE", "SCELLAGE", "SCHEIDAGE", "SCIAGE", "SCULPTAGE"]},
  {"label":"SE","words":["SÉCHAGE", "SECOUAGE", "SECRÉTAGE", "SELLAGE", "SEMELAGE", "SÉRANÇAGE", "SERFOUAGE", "SERINGAGE", "SERRAGE", "SERVAGE", "SEUILLAGE", "SEVRAGE", "SEXAGE"]},
  {"label":"SH","words":["SHUNTAGE"]},
  {"label":"SI","words":["SIFFLAGE", "SILLAGE", "SILOTAGE"]},
  {"label":"SM","words":["SMILLAGE"]},
  {"label":"SO","words":["SOLAGE", "SOLIDAGE", "SOLIVAGE", "SONDAGE", "SOUAGE", "SOUDAGE", "SOUFFLAGE", "SOUFRAGE", "SOUTIRAGE", "SOUTRAGE"]},
  {"label":"SP","words":["SPARAGE"]},
  {"label":"ST","words":["STAGE", "STELLAGE", "STÉNOSAGE", "STEPPAGE", "STÉRAGE", "STOCKAGE", "STOPPAGE", "STRIPAGE", "STUCAGE"]},
  {"label":"SU","words":["SUAGE", "SUCRAGE", "SUFFRAGE", "SULFATAGE", "SULFITAGE", "SULFURAGE", "SURDOSAGE", "SURFAÇAGE", "SURFILAGE", "SURMENAGE", "SURVIRAGE"]},
  {"label":"TAB","words":["TABASSAGE"]},
  {"label":"TAI","words":["TAILLAGE"]},
  {"label":"TAL","words":["TALLAGE", "TALOCHAGE", "TALONNAGE", "TALQUAGE", "TALUTAGE"]},
  {"label":"TAM","words":["TAMISAGE"]},
  {"label":"TAN","words":["TANGAGE", "TANISAGE", "TANNAGE", "TANNISAGE"]},
  {"label":"TAP","words":["TAPISSAGE", "TAPONNAGE", "TAPOTAGE"]},
  {"label":"TAQ","words":["TAQUAGE"]},
  {"label":"TAR","words":["TARAGE", "TARARAGE", "TARAUDAGE", "TARTRAGE"]},
  {"label":"TAS","words":["TASSAGE"]},
  {"label":"TAT","words":["TATOUAGE"]},
  {"label":"TAV","words":["TAVELAGE"]},
  {"label":"TAX","words":["TAXAGE"]},
  {"label":"TE","words":["TEILLAGE", "TÉLÉPÉAGE", "TÉLÉPHAGE", "TENONNAGE", "TERRAGE", "TESTAGE"]},
  {"label":"TI","words":["TIERÇAGE", "TILLAGE", "TIMBRAGE", "TIRAGE", "TISSAGE", "TITRAGE"]},
  {"label":"TO","words":["TOILAGE", "TONDAGE", "TONNAGE", "TONNELAGE", "TORDAGE", "TOUAGE", "TOUILLAGE", "TOURNAGE"]},
  {"label":"TRA","words":["TRAÇAGE", "TRACTAGE", "TRAÎNAGE", "TRAMAGE", "TRANCHAGE", "TRAPPAGE", "TRAVELAGE"]},
  {"label":"TRE","words":["TRÉFILAGE", "TRÉMATAGE", "TREMPAGE", "TRESSAGE"]},
  {"label":"TRI","words":["TRIAGE", "TRICOTAGE", "TRIPOTAGE"]},
  {"label":"TRO","words":["TROUSSAGE"]},
  {"label":"TRU","words":["TRUANDAGE", "TRUCAGE", "TRUQUAGE"]},
  {"label":"TU","words":["TUAGE", "TUBAGE", "TUILAGE", "TUNAGE", "TURBINAGE", "TUSSILAGE", "TUTEURAGE", "TUYAUTAGE"]},
  {"label":"TY","words":["TYPAGE"]},
  {"label":"US","words":["USAGÉ", "USINAGE"]},
  {"label":"VA","words":["VAIGRAGE", "VANISAGE", "VANNAGE", "VAPOTAGE", "VARLOPAGE", "VASSELAGE"]},
  {"label":"VE","words":["VEINAGE", "VÊLAGE", "VELTAGE", "VENTAGE", "VERBIAGE", "VERDAGE", "VERSAGE", "VÊTAGE", "VEUVAGE"]},
  {"label":"VI","words":["VIBRAGE", "VIDAGE", "VIGNETAGE", "VILLAGE", "VINAGE", "VINTAGE", "VIRAGE", "VIROLAGE", "VIROPHAGE", "VISAGE", "VISNAGE", "VISSAGE", "VITRAGE"]},
  {"label":"VO","words":["VOILAGE", "VOISINAGE", "VOITURAGE", "VOLAGE", "VOLIGEAGE", "VOLTAGE", "VOYAGEAGE"]},
  {"label":"VR","words":["VRILLAGE"]},
  {"label":"WA","words":["WAGAGE", "WAGONNAGE"]},
  {"label":"XY","words":["XYLOPHAGE"]},
  {"label":"ZE","words":["ZÉROTAGE"]},
  {"label":"ZI","words":["ZINCAGE", "ZINGAGE"]},
  {"label":"ZO","words":["ZONAGE", "ZOOPHAGE"]},
];

window.THEMODS_DATA.vi = [
  {"label":"AB","words":["ABERRER", "ABRÉAGIR"]},
  {"label":"AC","words":["ACCÉDER"]},
  {"label":"AD","words":["ADHÉRER"]},
  {"label":"AF","words":["AFFÉRER", "AFFLUER"]},
  {"label":"AG","words":["AGIOTER", "AGONISER"]},
  {"label":"AH","words":["AHANER"]},
  {"label":"AM","words":["AMBLER", "AMOUILLER"]},
  {"label":"AN","words":["ANHÉLER", "ANORDIR"]},
  {"label":"AP","words":["APPONTER"]},
  {"label":"AS","words":["ASSONER"]},
  {"label":"AT","words":["ATTENTER"]},
  {"label":"AV","words":["AVIRONNER", "AVOCASSER"]},
  {"label":"BAB","words":["BABILLER", "BABOLER"]},
  {"label":"BAD","words":["BADAUDER", "BADINER"]},
  {"label":"BAM","words":["BAMBOCHER"]},
  {"label":"BAN","words":["BANQUETER"]},
  {"label":"BAR","words":["BARÉTER", "BARJAQUER", "BAROUDER", "BARRIR"]},
  {"label":"BAS","words":["BASTER"]},
  {"label":"BAT","words":["BATAILLER", "BATIFOLER", "BATOILLER"]},
  {"label":"BAV","words":["BAVARDER", "BAVASSER"]},
  {"label":"BAY","words":["BAYER"]},
  {"label":"BE","words":["BEDONNER", "BÉER", "BÉGUETER", "BÊTISER"]},
  {"label":"BI","words":["BIBELOTER", "BICHER", "BIFURQUER", "BIQUER", "BISQUER"]},
  {"label":"BL","words":["BLABLATER", "BLATÉRER", "BLÉSER", "BLOGUER", "BLONDOYER"]},
  {"label":"BO","words":["BOITER", "BOITILLER", "BONDIR", "BOSTONNER", "BOTANISER", "BOUBOULER", "BOULOCHER", "BOURONNER"]},
  {"label":"BR","words":["BRASILLER", "BRILLER", "BRONCHER", "BRUISSER", "BRUNCHER"]},
  {"label":"CAB","words":["CABINER", "CABOTER", "CABOTINER", "CABRIOLER"]},
  {"label":"CAC","words":["CACABER", "CACARDER"]},
  {"label":"CAG","words":["CAGUER"]},
  {"label":"CAI","words":["CAILLETER"]},
  {"label":"CAL","words":["CALANCHER", "CALMIR", "CALUGER"]},
  {"label":"CAN","words":["CANCANER", "CANOTER"]},
  {"label":"CAP","words":["CAPÉER", "CAPEYER", "CAPITULER", "CAPONNER"]},
  {"label":"CAQ","words":["CAQUETER"]},
  {"label":"CAR","words":["CARACOLER", "CARTAYER"]},
  {"label":"CAS","words":["CASCADER"]},
  {"label":"CAT","words":["CATCHER"]},
  {"label":"CHA","words":["CHALUTER", "CHANCELER", "CHATONNER", "CHATOYER", "CHATTER", "CHAUVIR"]},
  {"label":"CHE","words":["CHENALER", "CHÉRER", "CHERRER", "CHEVRETER"]},
  {"label":"CHI","words":["CHIALER", "CHIBRER", "CHIGNER", "CHILLER", "CHINOISER"]},
  {"label":"CHL","words":["CHLINGUER"]},
  {"label":"CHN","words":["CHNEUQUER"]},
  {"label":"CHO","words":["CHOPINER", "CHOPPER", "CHOUANNER", "CHOUGNER", "CHOUINER"]},
  {"label":"CL","words":["CLAPOTER", "CLAQUETER", "CLAVARDER", "CLIGNOTER", "CLIQUETER", "CLOPINER", "CLOPPER"]},
  {"label":"COA","words":["COASSER"]},
  {"label":"COC","words":["COCONNER", "COCOTER", "COCOTTER"]},
  {"label":"COE","words":["COEXISTER"]},
  {"label":"COH","words":["COHABITER", "COHÉRITER"]},
  {"label":"COI","words":["COÏNCIDER", "COÏTER"]},
  {"label":"COK","words":["COKOTER"]},
  {"label":"COL","words":["COLLAPSER"]},
  {"label":"COM","words":["COMATER", "COMMERCER", "COMMÉRER", "COMPATIR", "COMPÉTER", "COMPÉTIR", "COMPLAIRE"]},
  {"label":"CON","words":["CONCORDER", "CONCOURIR", "CONFLUER", "CONSISTER", "CONSONER", "CONVERGER", "CONVERSER", "CONVOLER"]},
  {"label":"COO","words":["COOPÉRER"]},
  {"label":"COP","words":["COPINER", "COPULER"]},
  {"label":"COQ","words":["COQUETER"]},
  {"label":"COS","words":["COSSER"]},
  {"label":"COU","words":["COUCOUER", "COUCOULER", "COUINER", "COURATER"]},
  {"label":"CR","words":["CRAILLER", "CRAPOTER", "CRAQUETER", "CRÉCHER", "CRÉPITER", "CREVOTER", "CRIAILLER", "CRIQUER", "CRISER", "CRISSER", "CROASSER"]},
  {"label":"CU","words":["CULMINER"]},
  {"label":"DA","words":["DAIGNER", "DANSOTER", "DANSOTTER"]},
  {"label":"DEA","words":["DÉAMBULER"]},
  {"label":"DEB","words":["DÉBOUQUER"]},
  {"label":"DEC","words":["DÉCÉLÉRER", "DÉCHANTER", "DÉCOLÉRER", "DÉCONNER", "DÉCOUCHER", "DÉCOULER"]},
  {"label":"DEF","words":["DÉFAILLIR", "DÉFLAGRER", "DÉFUNTER"]},
  {"label":"DEG","words":["DÉGAMMER", "DÉGOUTTER"]},
  {"label":"DEH","words":["DÉHOTTER"]},
  {"label":"DEJ","words":["DÉJEUNER"]},
  {"label":"DEL","words":["DÉLIRER"]},
  {"label":"DEM","words":["DÉMÉRITER", "DÉMORDRE"]},
  {"label":"DEP","words":["DÉPARLER", "DÉPÉRIR", "DÉPLAIRE"]},
  {"label":"DER","words":["DÉRADER", "DÉRAGER", "DÉRAILLER", "DÉRAPER", "DÉROGER", "DÉRUPITER"]},
  {"label":"DET","words":["DÉTALER", "DÉTONER", "DÉTONNER"]},
  {"label":"DI","words":["DIFFLUER", "DIGRESSER", "DÎNER", "DINGUER", "DISCORDER", "DISCOURIR", "DISSERTER", "DISSONER", "DIVAGUER", "DIVERGER"]},
  {"label":"DU","words":["DUNKER"]},
  {"label":"EF","words":["EFFLUVER"]},
  {"label":"EM","words":["EMPIÉTER"]},
  {"label":"EN","words":["ENDÊVER"]},
  {"label":"ER","words":["ERRER"]},
  {"label":"ET","words":["ÉTERNUER", "ÉTINCELER", "ÊTRE"]},
  {"label":"EX","words":["EXCELLER", "EXCIPER", "EXISTER", "EXULTER"]},
  {"label":"FA","words":["FAIBLIR", "FASEILLER", "FASEYER"]},
  {"label":"FE","words":["FEULER"]},
  {"label":"FI","words":["FIENTER", "FINASSER"]},
  {"label":"FL","words":["FLAGEOLER", "FLAMBOYER", "FLANCHER", "FLÂNER", "FLEURETER", "FLIRTER", "FLOCONNER", "FLOCULER", "FLUCTUER", "FLUER"]},
  {"label":"FO","words":["FOISONNER", "FOLÂTRER", "FORLIGNER", "FORNIQUER", "FOUINER"]},
  {"label":"FR","words":["FRAÎCHIR", "FRÉMIR", "FRÉTILLER", "FROUER", "FROUILLER"]},
  {"label":"FU","words":["FUITER", "FULGURER", "FURETER"]},
  {"label":"GA","words":["GALÉJER", "GALÉRER", "GAMBADER", "GAMBILLER", "GAMINER", "GARGOTER", "GASCONNER", "GÂTIFIER"]},
  {"label":"GE","words":["GEEKER", "GEINDRE"]},
  {"label":"GL","words":["GLATIR", "GLOTTORER", "GLOUSSER"]},
  {"label":"GO","words":["GODAILLER", "GODILLER", "GOLFER", "GOUTTER"]},
  {"label":"GR","words":["GRAVITER", "GRELOTER", "GRELOTTER", "GRÉSILLER", "GRICHER", "GRIGNER", "GRINCER", "GRINCHER", "GRISOLER", "GRISOLLER", "GRISONNER", "GROOVER"]},
  {"label":"GU","words":["GUINCHER"]},
  {"label":"HA","words":["HÂBLER", "HALETER"]},
  {"label":"HE","words":["HENNIR", "HERCHER", "HERSCHER", "HÉSITER"]},
  {"label":"HI","words":["HIBERNER"]},
  {"label":"HO","words":["HOQUETER"]},
  {"label":"HU","words":["HULULER"]},
  {"label":"IM","words":["IMPLOSER"]},
  {"label":"IN","words":["INDAGUER", "INSISTER", "INTERAGIR"]},
  {"label":"IO","words":["IODLER", "IOULER"]},
  {"label":"IR","words":["IRONISER"]},
  {"label":"JA","words":["JABOTER", "JACASSER", "JAPPER", "JARGONNER", "JASSER"]},
  {"label":"JE","words":["JERKER"]},
  {"label":"JO","words":["JOBER", "JODLER", "JOGGER", "JONGLER", "JOUAILLER", "JOUIR", "JOUTER"]},
  {"label":"JU","words":["JUBILER", "JUMPER", "JUTER"]},
  {"label":"KO","words":["KOTER"]},
  {"label":"LA","words":["LAÏUSSER", "LAMBINER", "LAPINER", "LARMOYER"]},
  {"label":"LE","words":["LÉGIFÉRER", "LÉSINER", "LÉVITER"]},
  {"label":"LI","words":["LIARDER"]},
  {"label":"LO","words":["LOFER", "LOQUETER", "LOUCHIR", "LOUVETER", "LOUVOYER"]},
  {"label":"LU","words":["LUIRE", "LUNCHER", "LUTTER"]},
  {"label":"LY","words":["LYRER"]},
  {"label":"MA","words":["MARGAUDER", "MARGOTER", "MARGOTTER", "MARONNER", "MARRONNER"]},
  {"label":"ME","words":["MÉMÉRER", "MENTIR", "MERDOYER", "MÉSUSER", "MEUGLER"]},
  {"label":"MI","words":["MIAULER", "MILITER", "MINAUDER"]},
  {"label":"MO","words":["MOLARDER", "MOLLARDER", "MOTIONNER", "MOUFETER", "MOUFTER"]},
  {"label":"MU","words":["MUSARDER"]},
  {"label":"NA","words":["NAGEOTER", "NAVETTER", "NAVIGUER"]},
  {"label":"NI","words":["NIDIFIER"]},
  {"label":"NO","words":["NOCER", "NORDIR"]},
  {"label":"NU","words":["NUIRE"]},
  {"label":"OB","words":["OBLIQUER", "OBVIER"]},
  {"label":"OE","words":["ŒUVRER"]},
  {"label":"OF","words":["OFFICIER"]},
  {"label":"OP","words":["OPINER", "OPTER"]},
  {"label":"OR","words":["ORBITER"]},
  {"label":"OS","words":["OSCILLER"]},
  {"label":"OV","words":["OVULER"]},
  {"label":"PAC","words":["PACTISER"]},
  {"label":"PAG","words":["PAGAYER"]},
  {"label":"PAL","words":["PALABRER", "PALPITER"]},
  {"label":"PAN","words":["PANOTER", "PANTELER"]},
  {"label":"PAP","words":["PAPOTER"]},
  {"label":"PAR","words":["PARADER", "PARESSER", "PARLOTER", "PARTOUSER", "PARTOUZER"]},
  {"label":"PAT","words":["PATAUGER", "PATIENTER", "PÂTIR"]},
  {"label":"PAU","words":["PAUSER"]},
  {"label":"PE","words":["PÉCLOTER", "PÈDZER", "PENDILLER", "PÉPIER", "PERDURER", "PERFORMER", "PÉRORER", "PERSISTER", "PESTER", "PÉTARADER", "PÉTILLER", "PÉTOCHER", "PÉTUNER"]},
  {"label":"PI","words":["PIAFFER", "PIAILLER", "PIAPIATER", "PIAULER", "PINAILLER", "PINTOCHER", "PIONNER", "PIORNER", "PISSOTER", "PITUITER"]},
  {"label":"PL","words":["PLANCHER"]},
  {"label":"PO","words":["POGOTER", "POIROTER", "POITRINER", "PONTIFIER", "POTINER", "POUCER", "POUDROYER", "POUFFER", "POUGNER", "POULINER"]},
  {"label":"PR","words":["PRÉLUDER", "PROCÉDER", "PROFITER", "PROSPÉRER"]},
  {"label":"PS","words":["PSYCHOTER"]},
  {"label":"PU","words":["PULLULER", "PUPULER", "PUTASSER"]},
  {"label":"QU","words":["QUINTOYER"]},
  {"label":"RA","words":["RAFFOLER", "RAGER", "RAGOTER", "RÂLER", "RALLER", "RAMPER", "RAUQUER"]},
  {"label":"REA","words":["RÉAGIR"]},
  {"label":"REB","words":["REBIQUER"]},
  {"label":"REC","words":["RECAUSER", "RECHUTER"]},
  {"label":"RED","words":["REDONDER"]},
  {"label":"REE","words":["RÉER"]},
  {"label":"REF","words":["REFLUER"]},
  {"label":"REG","words":["RÉGATER", "RÉGNER", "REGORGER", "RÉGRESSER"]},
  {"label":"REL","words":["RELUIRE"]},
  {"label":"REM","words":["REMARCHER", "REMBRAYER", "REMÉDIER"]},
  {"label":"REN","words":["RENÂCLER", "RENARDER", "RENAUDER"]},
  {"label":"REP","words":["REPAIRER"]},
  {"label":"RES","words":["RÉSIDER", "RÉSISTER"]},
  {"label":"RET","words":["RETENTIR", "RETIGER", "RETONTIR", "RÉTROAGIR"]},
  {"label":"REV","words":["RÊVASSER"]},
  {"label":"RI","words":["RIBOULER", "RICANER", "RICOCHER", "RIGOLER", "RIOTER", "RIPAILLER", "RIRE", "RIVALISER"]},
  {"label":"RO","words":["RÔDAILLER", "ROGNONNER", "RONFLER", "ROQUER", "ROUGEOYER", "ROUMÉGUER", "ROUPILLER", "ROUSPÉTER"]},
  {"label":"RU","words":["RUTILER"]},
  {"label":"SA","words":["SALIVER", "SANGLOTER", "SAUTILLER"]},
  {"label":"SC","words":["SCHADER", "SCRABBLER"]},
  {"label":"SE","words":["SÉJOURNER", "SEMBLER", "SERPENTER", "SÉVIR"]},
  {"label":"SI","words":["SIÉGER", "SIESTER", "SILER"]},
  {"label":"SL","words":["SLALOMER"]},
  {"label":"SM","words":["SMURFER"]},
  {"label":"SO","words":["SOMBRER", "SOMNOLER", "SOUPER", "SOURIRE"]},
  {"label":"SP","words":["SPÉCULER", "SPORULER", "SPRINTER"]},
  {"label":"ST","words":["STAGNER"]},
  {"label":"SU","words":["SUBSISTER", "SUBVENIR", "SUCCÉDER", "SUCCOMBER", "SUFFIRE", "SURNAGER", "SURRÉAGIR", "SURSAUTER", "SURVIRER"]},
  {"label":"SW","words":["SWINGUER"]},
  {"label":"TA","words":["TAFFER", "TALLER", "TANGUER", "TAPAGER", "TAPINER", "TARDER", "TARTIR", "TÂTONNER"]},
  {"label":"TC","words":["TCHATER", "TCHATTER", "TCHOULER"]},
  {"label":"TE","words":["TEMPÊTER", "TERRIR"]},
  {"label":"TI","words":["TICTAQUER", "TIGER", "TILTER", "TIQUER", "TISER", "TITUBER"]},
  {"label":"TO","words":["TONITRUER", "TONNER", "TORAILLER", "TOSSER", "TOUPINER", "TOURNOYER", "TOUSSER", "TOUSSOTER"]},
  {"label":"TR","words":["TRABOULER", "TRALUIRE", "TRANSIGER", "TREKKER", "TRÉPIDER", "TRICOLER", "TRIMER", "TRINQUER", "TRIOMPHER", "TRIPER", "TRIPPER", "TRÔNER", "TROTTINER", "TROUILLER"]},
  {"label":"UL","words":["ULULER"]},
  {"label":"VA","words":["VACILLER", "VAGIR", "VAGUER", "VARAPPER", "VATICINER"]},
  {"label":"VE","words":["VÉGÉTER", "VÊLER", "VERDOYER", "VERMILLER", "VESSER", "VÉTILLER"]},
  {"label":"VI","words":["VIELLER", "VIRAILLER", "VIVOTER"]},
  {"label":"VO","words":["VOGUER", "VOISINER", "VOLETER", "VOLTER", "VOLTIGER", "VOYAGER"]},
  {"label":"VR","words":["VROMBIR"]},
  {"label":"YA","words":["YASSER"]},
  {"label":"YO","words":["YODLER", "YOUTSER", "YOUYOUTER", "YOYOTER", "YOYOTTER"]},
  {"label":"ZE","words":["ZÉZAYER"]},
  {"label":"ZI","words":["ZIGONNER", "ZIGZAGUER"]},
  {"label":"ZO","words":["ZOUKER", "ZOZOTER"]},
  {"label":"ZW","words":["ZWANZER"]},
];

window.THEMODS_DATA.oir = [
  {"label":"AB","words":["ABATTOIR", "ABREUVOIR"]},
  {"label":"AC","words":["ACCORDOIR", "ACCOTOIR", "ACCOUDOIR"]},
  {"label":"AF","words":["AFFILOIR", "AFFINOIR"]},
  {"label":"AI","words":["AIGUISOIR"]},
  {"label":"AJ","words":["AJUSTOIR"]},
  {"label":"AL","words":["ALÉSOIR", "ALLUMOIR"]},
  {"label":"AM","words":["AMORÇOIR"]},
  {"label":"AP","words":["APPAROIR", "APPUYOIR"]},
  {"label":"AR","words":["ARRACHOIR", "ARRÊTOIR", "ARROSOIR"]},
  {"label":"AS","words":["ASPERSOIR", "ASSAVOIR", "ASSEOIR", "ASSOIR", "ASSOMMOIR"]},
  {"label":"AT","words":["ATTISOIR"]},
  {"label":"AV","words":["AVALOIR", "AVOIR"]},
  {"label":"BA","words":["BATTOIR", "BAVARDOIR", "BAVOIR"]},
  {"label":"BE","words":["BÊCHOIR"]},
  {"label":"BL","words":["BLUTOIR"]},
  {"label":"BO","words":["BOBINOIR", "BONSOIR", "BOSSOIR", "BOUCHOIR", "BOUDOIR", "BOUGEOIR", "BOULOIR", "BOURROIR", "BOUTOIR"]},
  {"label":"BR","words":["BROCHOIR", "BRÛLOIR"]},
  {"label":"BU","words":["BUTOIR", "BUTTOIR"]},
  {"label":"CH","words":["CHALOIR", "CHANTOIR", "CHASSOIR", "CHAUFFOIR", "CHOIR"]},
  {"label":"CL","words":["CLAQUOIR"]},
  {"label":"CO","words":["COIR", "COMPAROIR", "COMPTOIR", "CONCEVOIR", "COUCHOIR", "COULOIR", "COUPOIR", "COUSOIR", "COUVOIR"]},
  {"label":"CR","words":["CRACHOIR"]},
  {"label":"CU","words":["CUEILLOIR"]},
  {"label":"DE","words":["DÉCEVOIR", "DÉCHOIR", "DÉCOUPOIR", "DÉFOULOIR", "DÉMÊLOIR", "DÉPOTOIR", "DÉSESPOIR", "DÉVALOIR", "DÉVERSOIR", "DÉVIDOIR", "DEVOIR"]},
  {"label":"DO","words":["DORTOIR"]},
  {"label":"DR","words":["DRAGEOIR", "DRAYOIR", "DRESSOIR"]},
  {"label":"EB","words":["ÉBARBOIR", "ÉBAUCHOIR", "ÉBOURROIR"]},
  {"label":"EC","words":["ÉCHARNOIR", "ÉCHAUDOIR", "ÉCHOIR", "ÉCLOSOIR", "ÉCORÇOIR", "ÉCRÉMOIR"]},
  {"label":"EG","words":["ÉGOUTTOIR", "ÉGRAPPOIR", "ÉGRUGEOIR"]},
  {"label":"EM","words":["ÉMONDOIR", "ÉMOUCHOIR", "ÉMOUVOIR"]},
  {"label":"EN","words":["ENCENSOIR", "ENFUMOIR", "ENRAYOIR", "ENTOIR", "ENTONNOIR", "ENTREVOIR"]},
  {"label":"EP","words":["ÉPANCHOIR", "ÉPISSOIR", "ÉPLUCHOIR"]},
  {"label":"ES","words":["ESPOIR"]},
  {"label":"ET","words":["ÉTEIGNOIR", "ÉTENDOIR", "ÉTOUFFOIR"]},
  {"label":"EV","words":["ÉVIDOIR"]},
  {"label":"FA","words":["FALLOIR"]},
  {"label":"FE","words":["FENDOIR", "FERMOIR"]},
  {"label":"FI","words":["FICHOIR"]},
  {"label":"FO","words":["FONDOIR", "FOSSOIR", "FOULOIR", "FOUTOIR"]},
  {"label":"FR","words":["FRAISOIR", "FRAYOIR", "FROTTOIR"]},
  {"label":"FU","words":["FUMOIR"]},
  {"label":"GA","words":["GAUFROIR"]},
  {"label":"GE","words":["GERMOIR"]},
  {"label":"GL","words":["GLISSOIR"]},
  {"label":"GR","words":["GRATTOIR", "GRAVOIR", "GREFFOIR", "GRÉSOIR", "GRIFFOIR", "GRILLOIR", "GRUGEOIR"]},
  {"label":"GU","words":["GUEULOIR", "GUIPOIR"]},
  {"label":"HA","words":["HACHOIR", "HÂLOIR"]},
  {"label":"HE","words":["HEURTOIR"]},
  {"label":"HO","words":["HOIR", "HOUSSOIR"]},
  {"label":"IS","words":["ISOLOIR"]},
  {"label":"JA","words":["JABLOIR"]},
  {"label":"JU","words":["JUCHOIR"]},
  {"label":"LA","words":["LAMINOIR", "LAVOIR"]},
  {"label":"LI","words":["LINÇOIR", "LINSOIR", "LISSOIR"]},
  {"label":"LO","words":["LOIR"]},
  {"label":"LU","words":["LUSTROIR"]},
  {"label":"MA","words":["MANOIR", "MARGEOIR", "MARQUOIR", "MATOIR"]},
  {"label":"ME","words":["MESSEOIR", "MESSOIR"]},
  {"label":"MI","words":["MIROIR"]},
  {"label":"MO","words":["MOLETOIR", "MONTOIR", "MOUCHOIR", "MOUILLOIR", "MOUROIR", "MOUSSOIR", "MOUVOIR"]},
  {"label":"MU","words":["MUSOIR"]},
  {"label":"NI","words":["NICHOIR"]},
  {"label":"NO","words":["NOIR"]},
  {"label":"OS","words":["OSTENSOIR"]},
  {"label":"OU","words":["OUVROIR"]},
  {"label":"PA","words":["PARLOIR", "PAROIR"]},
  {"label":"PE","words":["PEIGNOIR", "PENDOIR", "PERCEVOIR", "PERCHOIR", "PERÇOIR", "PERLOIR"]},
  {"label":"PI","words":["PIQUOIR", "PISSOIR"]},
  {"label":"PL","words":["PLANOIR", "PLANTOIR", "PLEUVOIR", "PLIOIR", "PLOMBOIR", "PLONGEOIR"]},
  {"label":"PO","words":["POCHOIR", "POLISSOIR", "PONDOIR", "PORTOIR", "POURVOIR", "POUSSOIR", "POUVOIR"]},
  {"label":"PR","words":["PRESSOIR", "PRÉVALOIR", "PRÉVOIR", "PROMENOIR"]},
  {"label":"PU","words":["PUISOIR", "PURGEOIR"]},
  {"label":"RA","words":["RABATTOIR", "RACLOIR", "RASOIR", "RASSEOIR", "RASSOIR", "RAVOIR"]},
  {"label":"REB","words":["REBONSOIR"]},
  {"label":"REC","words":["RECEVOIR", "RECULOIR /"]},
  {"label":"RED","words":["REDEVOIR"]},
  {"label":"REF","words":["REFOULOIR"]},
  {"label":"REG","words":["RÉGLOIR"]},
  {"label":"REM","words":["REMONTOIR"]},
  {"label":"REP","words":["REPOSOIR"]},
  {"label":"RES","words":["RÉSERVOIR"]},
  {"label":"RET","words":["RETENDOIR", "RETORDOIR", "RETORSOIR"]},
  {"label":"REV","words":["REVALOIR", "REVERDOIR", "REVERSOIR", "REVOIR /", "REVOULOIR"]},
  {"label":"RI","words":["RIDOIR", "RIFLOIR", "RIVOIR"]},
  {"label":"RO","words":["RODOIR", "ROGNOIR", "ROUISSOIR", "ROULOIR"]},
  {"label":"SA","words":["SAIGNOIR", "SALOIR", "SARCLOIR", "SAUTOIR", "SAVOIR"]},
  {"label":"SE","words":["SÉCHOIR", "SEMOIR", "SEOIR", "SÉRANÇOIR"]},
  {"label":"SO","words":["SOIR", "SOUFROIR"]},
  {"label":"SU","words":["SUÇOIR", "SURSEOIR", "SURSOIR"]},
  {"label":"TA","words":["TAILLOIR", "TAMANOIR", "TAQUOIR"]},
  {"label":"TE","words":["TENDOIR", "TERROIR"]},
  {"label":"TI","words":["TIROIR"]},
  {"label":"TO","words":["TORDOIR"]},
  {"label":"TR","words":["TRAÇOIR", "TRANCHOIR", "TROTTOIR"]},
  {"label":"UR","words":["URINOIR"]},
  {"label":"VA","words":["VALOIR"]},
  {"label":"VE","words":["VERSOIR"]},
  {"label":"VI","words":["VIDOIR", "VIVOIR"]},
  {"label":"VO","words":["VOIR", "VOULOIR", "VOUSSOIR"]},
];

window.THEMODS_DATA.able = [
  {"label":"AB","words":["ABATTABLE", "ABLE", "ABORDABLE"]},
  {"label":"AC","words":["ACCABLE", "ACCUSABLE", "ACHETABLE", "ACTIVABLE"]},
  {"label":"AD","words":["ADAPTABLE", "ADMIRABLE", "ADOPTABLE", "ADORABLE"]},
  {"label":"AE","words":["AÉROCÂBLE"]},
  {"label":"AF","words":["AFFABLE"]},
  {"label":"AG","words":["AGRÉABLE"]},
  {"label":"AI","words":["AIMABLE"]},
  {"label":"AJ","words":["AJUSTABLE"]},
  {"label":"AL","words":["ALIÉNABLE", "ALLOUABLE", "ALTÉRABLE"]},
  {"label":"AM","words":["AMENDABLE", "AMIABLE"]},
  {"label":"AN","words":["ANNULABLE"]},
  {"label":"AP","words":["APPELABLE"]},
  {"label":"AR","words":["ARABLE", "ARROSABLE"]},
  {"label":"AS","words":["ASSURABLE", "ASTABLE"]},
  {"label":"AT","words":["ATTABLE", "ATTIRABLE"]},
  {"label":"AV","words":["AVALABLE", "AVOUABLE"]},
  {"label":"BA","words":["BAISABLE", "BANCABLE", "BANKABLE", "BANQUABLE", "BATTABLE"]},
  {"label":"BI","words":["BISTABLE"]},
  {"label":"BL","words":["BLÂMABLE"]},
  {"label":"BU","words":["BUVABLE"]},
  {"label":"CA","words":["CÂBLE", "CANOTABLE", "CAPABLE", "CAPTABLE", "CARTABLE", "CASSABLE"]},
  {"label":"CE","words":["CERNABLE"]},
  {"label":"CH","words":["CHABLE", "CHANTABLE", "CHASSABLE", "CHÉQUABLE", "CHÔMABLE"]},
  {"label":"CL","words":["CLASSABLE", "CLIPSABLE", "CLIQUABLE", "CLIVABLE"]},
  {"label":"CO","words":["COLLABLE", "COMMUABLE", "COMPTABLE", "CONGÉABLE", "CONSTABLE", "COPIABLE", "CORVÉABLE", "COTABLE", "COUPABLE"]},
  {"label":"CR","words":["CROYABLE"]},
  {"label":"CU","words":["CUBABLE", "CUMULABLE", "CURABLE"]},
  {"label":"CY","words":["CYCLABLE"]},
  {"label":"DA","words":["DAMNABLE", "DANSABLE", "DATABLE"]},
  {"label":"DE","words":["DÉBITABLE", "DECABLE", "DÉCELABLE", "DÉCIDABLE", "DÉPLIABLE", "DÉRIVABLE", "DÉSIRABLE", "DESSABLE", "DEVINABLE"]},
  {"label":"DI","words":["DIABLE", "DIGÉRABLE", "DILATABLE", "DISABLE"]},
  {"label":"DO","words":["DOMPTABLE", "DOSABLE"]},
  {"label":"DU","words":["DURABLE"]},
  {"label":"EC","words":["ÉCOUTABLE"]},
  {"label":"ED","words":["ÉDITABLE", "ÉDUCABLE"]},
  {"label":"EF","words":["EFFAÇABLE"]},
  {"label":"EG","words":["ÉGALABLE"]},
  {"label":"EJ","words":["ÉJECTABLE"]},
  {"label":"EM","words":["EMPILABLE"]},
  {"label":"EN","words":["ENDIABLÉ", "ENDURABLE", "ENSABLE", "ENTABLE", "ENVIABLE"]},
  {"label":"EP","words":["ÉPUISABLE"]},
  {"label":"EQ","words":["ÉQUITABLE"]},
  {"label":"ER","words":["ÉRABLE"]},
  {"label":"ES","words":["ESTIMABLE"]},
  {"label":"ET","words":["ÉTABLE", "ÉTIRABLE"]},
  {"label":"EV","words":["ÉVALUABLE", "ÉVITABLE", "ÉVOCABLE"]},
  {"label":"EX","words":["EXCITABLE", "EXCUSABLE", "EXÉCRABLE", "EXPIABLE"]},
  {"label":"FA","words":["FABLE", "FAISABLE", "FATIGABLE", "FAVORABLE"]},
  {"label":"FE","words":["FÊTABLE", "FEUTRABLE"]},
  {"label":"FI","words":["FIABLE", "FILABLE", "FILMABLE", "FILTRABLE", "FIXABLE"]},
  {"label":"FL","words":["FLOTTABLE"]},
  {"label":"FO","words":["FORABLE", "FORGEABLE", "FORMABLE"]},
  {"label":"FR","words":["FRIABLE"]},
  {"label":"FU","words":["FUMABLE"]},
  {"label":"GA","words":["GABLE", "GAGNABLE"]},
  {"label":"GE","words":["GÉRABLE"]},
  {"label":"GO","words":["GONFLABLE", "GOURNABLE"]},
  {"label":"GR","words":["GRACIABLE"]},
  {"label":"GU","words":["GUÉABLE"]},
  {"label":"HA","words":["HABITABLE", "HABLE", "HAÏSSABLE"]},
  {"label":"HE","words":["HÉRITABLE"]},
  {"label":"HO","words":["HONORABLE"]},
  {"label":"IM","words":["IMBITABLE", "IMBUVABLE", "IMITABLE", "IMMUABLE", "IMPARABLE", "IMPAYABLE", "IMPOSABLE", "IMPUTABLE"]},
  {"label":"INC","words":["INCAPABLE", "INCASABLE", "INCUNABLE", "INCURABLE"]},
  {"label":"IND","words":["INDATABLE", "INDEXABLE"]},
  {"label":"INE","words":["INEFFABLE"]},
  {"label":"INF","words":["INFUMABLE"]},
  {"label":"ING","words":["INGÉRABLE"]},
  {"label":"INH","words":["INHALABLE"]},
  {"label":"INJ","words":["INJOUABLE"]},
  {"label":"INL","words":["INLOUABLE"]},
  {"label":"INO","words":["INONDABLE"]},
  {"label":"INR","words":["INRATABLE", "INRAYABLE"]},
  {"label":"INS","words":["INSÉCABLE", "INSÉRABLE", "INSTABLE"]},
  {"label":"INT","words":["INTENABLE"]},
  {"label":"INU","words":["INUSABLE"]},
  {"label":"INV","words":["INVIVABLE"]},
  {"label":"IR","words":["IRISABLE", "IRRIGABLE", "IRRITABLE"]},
  {"label":"IS","words":["ISOLABLE"]},
  {"label":"JA","words":["JABLE"]},
  {"label":"JE","words":["JETABLE"]},
  {"label":"JO","words":["JOIGNABLE", "JOUABLE"]},
  {"label":"JU","words":["JUGEABLE", "JURABLE"]},
  {"label":"KA","words":["KAYAKABLE"]},
  {"label":"LA","words":["LARGABLE", "LAVABLE"]},
  {"label":"LI","words":["LIBÉRABLE", "LIMITABLE", "LIVRABLE"]},
  {"label":"LO","words":["LOGEABLE", "LOUABLE"]},
  {"label":"MA","words":["MALLÉABLE", "MANGEABLE", "MANIABLE", "MARIABLE"]},
  {"label":"ME","words":["MÉMORABLE", "MESURABLE", "METTABLE"]},
  {"label":"MI","words":["MINABLE", "MISÉRABLE"]},
  {"label":"MO","words":["MODELABLE", "MODÉRABLE", "MODULABLE", "MONOCÂBLE", "MONTABLE", "MONTRABLE", "MOULABLE"]},
  {"label":"MU","words":["MUTABLE"]},
  {"label":"NA","words":["NABLE", "NAVIGABLE"]},
  {"label":"NI","words":["NIABLE"]},
  {"label":"NO","words":["NOMBRABLE", "NOTABLE"]},
  {"label":"OP","words":["OPÉABLE", "OPÉRABLE", "OPPOSABLE"]},
  {"label":"OU","words":["OUBLIABLE", "OUVRABLE"]},
  {"label":"OX","words":["OXYDABLE"]},
  {"label":"PA","words":["PALPABLE", "PAPABLE", "PARLABLE", "PASSABLE", "PÂTURABLE", "PAYABLE"]},
  {"label":"PE","words":["PECCABLE", "PÊCHABLE", "PENDABLE", "PENSABLE", "PERDABLE", "PERMÉABLE"]},
  {"label":"PI","words":["PITOYABLE"]},
  {"label":"PL","words":["PLAÇABLE", "PLAIDABLE", "PLIABLE", "PLOYABLE"]},
  {"label":"PO","words":["PORTABLE", "POTABLE"]},
  {"label":"PR","words":["PRÉALABLE", "PRENABLE", "PRÊTABLE", "PROBABLE", "PROUVABLE"]},
  {"label":"PU","words":["PUBLIABLE"]},
  {"label":"QU","words":["QUARRABLE", "QUÉRABLE"]},
  {"label":"RA","words":["RÂBLÉ", "RANIMABLE"]},
  {"label":"REC","words":["RECEVABLE", "RÉCUSABLE"]},
  {"label":"RED","words":["REDEVABLE"]},
  {"label":"REF","words":["REFUSABLE", "RÉFUTABLE"]},
  {"label":"REG","words":["RÉGLABLE"]},
  {"label":"REJ","words":["REJETABLE"]},
  {"label":"REL","words":["RELÉGABLE", "RELEVABLE"]},
  {"label":"REM","words":["REMUABLE"]},
  {"label":"REN","words":["RENTABLE"]},
  {"label":"REP","words":["RÉPARABLE", "REPÉRABLE", "REPLIABLE"]},
  {"label":"RES","words":["RÉSÉCABLE"]},
  {"label":"RET","words":["RETABLE", "RETIRABLE"]},
  {"label":"REV","words":["RÉVISABLE", "RÉVOCABLE"]},
  {"label":"RO","words":["ROUABLE"]},
  {"label":"SA","words":["SABLÉ", "SATURABLE"]},
  {"label":"SC","words":["SCIABLE"]},
  {"label":"SE","words":["SÉCABLE", "SEMBLABLE", "SÉPARABLE", "SERVIABLE"]},
  {"label":"SK","words":["SKIABLE"]},
  {"label":"SO","words":["SOCIABLE", "SOIGNABLE", "SOLVABLE", "SOMMABLE", "SORTABLE", "SOUDABLE"]},
  {"label":"ST","words":["STABLE", "STOCKABLE"]},
  {"label":"TA","words":["TABLE", "TAILLABLE", "TAXABLE"]},
  {"label":"TE","words":["TENABLE", "TESTABLE"]},
  {"label":"TO","words":["TOLÉRABLE", "TOUCHABLE"]},
  {"label":"TR","words":["TRAÇABLE", "TRACTABLE", "TRAITABLE", "TROUVABLE"]},
  {"label":"TU","words":["TUABLE"]},
  {"label":"US","words":["USABLE", "USINABLE"]},
  {"label":"VA","words":["VALABLE", "VARIABLE"]},
  {"label":"VE","words":["VENDABLE", "VÉNÉRABLE", "VÉRITABLE"]},
  {"label":"VI","words":["VIABLE", "VICIABLE", "VIOLABLE", "VISITABLE", "VISSABLE", "VIVABLE"]},
  {"label":"VO","words":["VOCABLE", "VOLABLE"]},
  {"label":"ZI","words":["ZIRABLE"]},
  {"label":"ZO","words":["ZOOMABLE"]},
];

window.THEMODS_DATA.ique = [
  {"label":"AB","words":["ABDIQUE", "ABIOTIQUE", "ABOULIQUE"]},
  {"label":"AC","words":["ACÉTIQUE", "ACLINIQUE", "ACNÉIQUE", "ACRYLIQUE", "ACTINIQUE", "ACYCLIQUE"]},
  {"label":"AD","words":["ADAMIQUE", "ADIPIQUE"]},
  {"label":"AE","words":["AÉROBIQUE"]},
  {"label":"AF","words":["AFFRIQUÉ"]},
  {"label":"AG","words":["AGNATIQUE", "AGNOSIQUE", "AGOGIQUE", "AGONIQUE"]},
  {"label":"AL","words":["ALAMBIQUE", "ALCAÏQUE", "ALÉTHIQUE", "ALEXIQUE", "ALGINIQUE", "ALGIQUE", "ALIOTIQUE", "ALLÉLIQUE", "ALLYLIQUE", "ALOÉTIQUE", "ALOGIQUE", "ALTAÏQUE"]},
  {"label":"AM","words":["AMHARIQUE", "AMIMIQUE", "AMNÉSIQUE", "AMYLIQUE"]},
  {"label":"AN","words":["ANÉMIQUE", "ANERGIQUE", "ANGÉLIQUE", "ANIONIQUE", "ANODIQUE", "ANOMIQUE", "ANOSMIQUE", "ANOXIQUE", "ANTIQUE", "ANURIQUE"]},
  {"label":"AO","words":["AORTIQUE"]},
  {"label":"AP","words":["APATHIQUE", "APHASIQUE", "APIQUE", "APLASIQUE", "APNÉIQUE", "APPLIQUE", "APRAXIQUE"]},
  {"label":"AQ","words":["AQUATIQUE"]},
  {"label":"AR","words":["ARABIQUE", "ARCHAÏQUE", "ARCTIQUE", "ARÉIQUE", "ARGOTIQUE", "ARSÉNIQUE"]},
  {"label":"AS","words":["ASCÉTIQUE", "ASCITIQUE", "ASEPTIQUE", "ASIATIQUE", "ASISMIQUE", "ASTATIQUE", "ASTIQUE"]},
  {"label":"AT","words":["ATAVIQUE", "ATAXIQUE", "ATHYMIQUE", "ATOMIQUE", "ATONIQUE", "ATOPIQUE", "ATOXIQUE", "ATTIQUE", "ATTRIQUE", "ATYPIQUE"]},
  {"label":"AU","words":["AULIQUE", "AURIQUE"]},
  {"label":"AV","words":["AVESTIQUE", "AVIONIQUE"]},
  {"label":"AX","words":["AXÉNIQUE"]},
  {"label":"AZ","words":["AZOÏQUE", "AZOTIQUE"]},
  {"label":"BA","words":["BABÉLIQUE", "BACHIQUE", "BALTIQUE", "BARÉMIQUE", "BARRIQUE", "BASILIQUE", "BASIQUE", "BATAVIQUE"]},
  {"label":"BE","words":["BÉCHIQUE", "BÉNÉFIQUE", "BENTHIQUE", "BENZOÏQUE", "BERNIQUE"]},
  {"label":"BI","words":["BIBASIQUE", "BIBLIQUE", "BICHIQUE", "BICONIQUE", "BIONIQUE", "BIOPSIQUE", "BIOTIQUE", "BIQUE"]},
  {"label":"BO","words":["BORIQUÉ", "BOTANIQUE", "BOTULIQUE", "BOURRIQUE", "BOUTIQUE"]},
  {"label":"BR","words":["BRIQUE", "BROMIQUE"]},
  {"label":"BU","words":["BUBONIQUE", "BUCOLIQUE", "BUTYLIQUE", "BUTYRIQUE"]},
  {"label":"CA","words":["CACIQUE", "CAÏQUE", "CALCIQUE", "CALORIQUE", "CANONIQUE", "CANTIQUE", "CAPRIQUE", "CAPROÏQUE", "CARABIQUE", "CAUSTIQUE"]},
  {"label":"CE","words":["CELTIQUE", "CÉRAMIQUE", "CÉRIQUE", "CÉTONIQUE"]},
  {"label":"CH","words":["CHAOTIQUE", "CHIATIQUE", "CHIMIQUE", "CHIQUÉ", "CHLORIQUE", "CHOLIQUE", "CHORÉIQUE", "CHROMIQUE", "CHRONIQUE"]},
  {"label":"CI","words":["CINÉTIQUE", "CITRIQUE", "CIVIQUE"]},
  {"label":"CL","words":["CLANIQUE", "CLASSIQUE", "CLASTIQUE", "CLAUDIQUE", "CLINIQUE", "CLIQUE", "CLONIQUE"]},
  {"label":"CO","words":["COBOTIQUE", "COLCHIQUE", "COLÉRIQUE", "COLIQUE", "COMÉTIQUE", "COMIQUE", "COMPLIQUE", "CONIQUE", "CORANIQUE", "CORNIQUE", "COSMIQUE", "COUFIQUE"]},
  {"label":"CR","words":["CRAMIQUE", "CRÉATIQUE", "CRÉTIQUE", "CRIQUE", "CRITIQUE", "CRYPTIQUE"]},
  {"label":"CU","words":["CUBIQUE", "CUIVRIQUE", "CUPRIQUE"]},
  {"label":"CY","words":["CYANIQUE", "CYCLIQUE", "CYMRIQUE", "CYNIQUE", "CYSTIQUE"]},
  {"label":"DA","words":["DACITIQUE", "DARIQUE"]},
  {"label":"DE","words":["DÉCYLIQUE", "DÉICTIQUE", "DELPHIQUE", "DELTAÏQUE", "DÉMOTIQUE", "DÉONTIQUE", "DEPIQUE", "DERMIQUE", "DÉTONIQUE", "DETOXIQUE"]},
  {"label":"DI","words":["DIAZOÏQUE", "DIBASIQUE", "DIÉNIQUE", "DIOÏQUE", "DISTIQUE"]},
  {"label":"DO","words":["DOLIQUE", "DOMOTIQUE", "DORIQUE"]},
  {"label":"DR","words":["DRASTIQUE", "DRUIDIQUE"]},
  {"label":"DU","words":["DUPLIQUE"]},
  {"label":"DY","words":["DYADIQUE", "DYNAMIQUE", "DYSURIQUE", "DYTIQUE"]},
  {"label":"EB","words":["EBRIQUE"]},
  {"label":"EC","words":["ECTOPIQUE"]},
  {"label":"ED","words":["ÉDAPHIQUE", "ÉDÉNIQUE", "ÉDITIQUE"]},
  {"label":"EG","words":["ÉGOTIQUE"]},
  {"label":"EI","words":["EIDÉTIQUE"]},
  {"label":"EL","words":["ÉLASTIQUÉ", "ÉLÉATIQUE", "ELFIQUE"]},
  {"label":"EM","words":["EMBOLIQUE", "ÉMÉTIQUE", "EMPIRIQUE"]},
  {"label":"EN","words":["ENDÉMIQUE", "ÉNERGIQUE", "ENTÉRIQUE"]},
  {"label":"EO","words":["ÉOLIQUE"]},
  {"label":"EP","words":["ÉPIQUE"]},
  {"label":"ER","words":["ERADIQUE", "ÉRISTIQUE", "ÉROTIQUE", "ERRATIQUE", "ÉRUCIQUE"]},
  {"label":"ES","words":["ÉSOPIQUE"]},
  {"label":"ET","words":["ÉTATIQUE", "ÉTHIQUE", "ETHNIQUE", "ÉTHYLIQUE", "ÉTIQUE", "ETRIQUE"]},
  {"label":"EU","words":["EUGÉNIQUE", "EUPNÉIQUE", "EUTOCIQUE"]},
  {"label":"EX","words":["EXORÉIQUE", "EXOTIQUE", "EXPLIQUE", "EXTATIQUE"]},
  {"label":"FA","words":["FABRIQUE", "FALARIQUE", "FAMÉLIQUE", "FANATIQUE", "FARADIQUE", "FATIDIQUE", "FAUNIQUE", "FAVIQUE"]},
  {"label":"FE","words":["FÉERIQUE", "FERRIQUE"]},
  {"label":"FI","words":["FILMIQUE"]},
  {"label":"FL","words":["FLIQUE", "FLUIDIQUE"]},
  {"label":"FO","words":["FOLIQUE", "FONGIQUE", "FORMIQUE", "FORNIQUE"]},
  {"label":"FR","words":["FRANCIQUE", "FRIQUÉ"]},
  {"label":"FU","words":["FUMARIQUE"]},
  {"label":"GA","words":["GABEGIQUE", "GAÉLIQUE", "GALÉNIQUE", "GALLIQUE", "GAMÉTIQUE", "GASTRIQUE"]},
  {"label":"GE","words":["GÉNÉRIQUE", "GÉNÉSIQUE", "GÉNÉTIQUE", "GÉNIQUE", "GÉNOMIQUE", "GÉORGIQUE", "GESTIQUE"]},
  {"label":"GL","words":["GLOBIQUE", "GLOTTIQUE", "GLYPTIQUE"]},
  {"label":"GN","words":["GNOMIQUE", "GNOSIQUE", "GNOSTIQUE"]},
  {"label":"GO","words":["GOLFIQUE", "GONADIQUE", "GOTHIQUE", "GOTIQUE"]},
  {"label":"GR","words":["GRAPHIQUE", "GRIOTIQUE"]},
  {"label":"GY","words":["GYMNIQUE"]},
  {"label":"HA","words":["HAPTIQUE"]},
  {"label":"HE","words":["HÉBRAÏQUE", "HECTIQUE", "HÉDONIQUE", "HÉMATIQUE", "HÉMIQUE", "HÉPATIQUE", "HÉRÉTIQUE", "HÉROÏQUE"]},
  {"label":"HI","words":["HIPPIQUE"]},
  {"label":"HO","words":["HOMÉRIQUE"]},
  {"label":"HU","words":["HUMIQUE", "HUNNIQUE"]},
  {"label":"HY","words":["HYDATIQUE", "HYDRIQUE", "HYLÉTIQUE", "HYMNIQUE", "HYPOXIQUE"]},
  {"label":"IA","words":["IAMBIQUE"]},
  {"label":"IB","words":["IBÉRIQUE"]},
  {"label":"IC","words":["ICONIQUE", "ICTÉRIQUE"]},
  {"label":"ID","words":["IDENTIQUE", "IDYLLIQUE"]},
  {"label":"IL","words":["ILLOGIQUE"]},
  {"label":"IM","words":["IMAGOÏQUE", "IMBRIQUE", "IMPLIQUE", "IMPUDIQUE"]},
  {"label":"IN","words":["INCASIQUE", "INCIVIQUE", "INDIQUE", "INDOLIQUE", "INIQUE", "INTOXIQUE", "INTRIQUE"]},
  {"label":"IO","words":["IODIQUE", "IONIQUE"]},
  {"label":"IR","words":["IRÉNIQUE", "IRONIQUE"]},
  {"label":"IS","words":["ISLAMIQUE", "ISTHMIQUE"]},
  {"label":"IT","words":["ITALIQUE"]},
  {"label":"JA","words":["JAZZIQUE"]},
  {"label":"JU","words":["JUDAÏQUE", "JURIDIQUE"]},
  {"label":"KA","words":["KARMIQUE", "KARSTIQUE"]},
  {"label":"KE","words":["KÉRATIQUE"]},
  {"label":"KI","words":["KINÉSIQUE"]},
  {"label":"KU","words":["KUFIQUE"]},
  {"label":"KY","words":["KYMRIQUE", "KYSTIQUE"]},
  {"label":"LA","words":["LACONIQUE", "LACTIQUE", "LAÏQUE", "LAMAÏQUE", "LAVIQUE"]},
  {"label":"LE","words":["LÉMANIQUE", "LÉVITIQUE", "LEXIQUE"]},
  {"label":"LI","words":["LIASIQUE", "LIMBIQUE", "LIMNIQUE", "LINÉIQUE", "LIPIDIQUE", "LITANIQUE", "LITHIQUE"]},
  {"label":"LO","words":["LŒSSIQUE", "LOGIQUE"]},
  {"label":"LU","words":["LUBRIQUE", "LUDIQUE", "LUNATIQUE", "LUPIQUE"]},
  {"label":"LY","words":["LYRIQUE", "LYTIQUE"]},
  {"label":"MA","words":["MAGIQUE", "MAÏOLIQUE", "MAJOLIQUE", "MALÉFIQUE", "MALÉIQUE", "MALIQUE", "MALONIQUE", "MANIQUE", "MANTIQUE", "MAROTIQUE", "MASSIQUE", "MASTIQUE"]},
  {"label":"ME","words":["MÉCANIQUE", "MÉDIQUE", "MÉGARIQUE", "MÉIOTIQUE", "MÉLANIQUE", "MÉLIQUE", "MÉLODIQUE", "MERDIQUE", "MÉTOPIQUE", "MÉTRIQUE"]},
  {"label":"MI","words":["MIMÉTIQUE", "MIMIQUE", "MIQUE", "MIRIFIQUE", "MITOTIQUE"]},
  {"label":"MN","words":["MNÉSIQUE"]},
  {"label":"MO","words":["MODIQUE", "MONÉTIQUE", "MONODIQUE", "MONOÏQUE", "MOSAÏQUE", "MOUSTIQUE"]},
  {"label":"MU","words":["MUONIQUE", "MUSIQUE", "MUTIQUE"]},
  {"label":"MY","words":["MYALGIQUE", "MYCOSIQUE", "MYOTIQUE", "MYSTIQUE", "MYTHIQUE"]},
  {"label":"NA","words":["NASIQUE", "NAUTIQUE"]},
  {"label":"NE","words":["NÉMATIQUE", "NÉOZOÏQUE", "NÉRITIQUE"]},
  {"label":"NI","words":["NILOTIQUE", "NIQUE", "NITRIQUE"]},
  {"label":"NO","words":["NOÉTIQUE", "NORDIQUE", "NOVOTIQUE"]},
  {"label":"NU","words":["NUCLÉIQUE", "NUMÉRIQUE", "NURAGIQUE"]},
  {"label":"OB","words":["OBLIQUE"]},
  {"label":"OC","words":["OCÉANIQUE"]},
  {"label":"OE","words":["ŒNOLIQUE"]},
  {"label":"OG","words":["OGAMIQUE", "OGHAMIQUE"]},
  {"label":"OH","words":["OHMIQUE"]},
  {"label":"OL","words":["OLÉIQUE", "OLYMPIQUE"]},
  {"label":"OM","words":["OMBILIQUÉ"]},
  {"label":"ON","words":["ONCOTIQUE", "ONIRIQUE", "ONKOTIQUE", "ONTIQUE"]},
  {"label":"OO","words":["OOLITIQUE"]},
  {"label":"OP","words":["OPSONIQUE", "OPTIQUE"]},
  {"label":"OR","words":["ORDALIQUE", "ORGANIQUE", "ORPHIQUE"]},
  {"label":"OS","words":["OSIDIQUE", "OSMIQUE", "OSMOTIQUE"]},
  {"label":"OT","words":["OTALGIQUE", "OTIQUE"]},
  {"label":"OX","words":["OXALIQUE"]},
  {"label":"PA","words":["PACIFIQUE", "PALUDIQUE", "PANIQUE", "PARÉTIQUE", "PARODIQUE"]},
  {"label":"PE","words":["PECTIQUE", "PÉLAGIQUE", "PEPTIQUE", "PERSIQUE"]},
  {"label":"PH","words":["PHALLIQUE", "PHASIQUE", "PHATIQUE", "PHÉNIQUÉ", "PHOBIQUE", "PHONIQUE", "PHOTIQUE", "PHRÉNIQUE", "PHTALIQUE", "PHTISIQUE", "PHYSIQUE"]},
  {"label":"PI","words":["PICRIQUE", "PIQUÉ"]},
  {"label":"PL","words":["PLASMIQUE", "PLASTIQUE", "PLIQUE"]},
  {"label":"PO","words":["POÉTIQUE", "POLÉMIQUE", "POLITIQUE", "PORTIQUE"]},
  {"label":"PR","words":["PRATIQUE", "PRAXIQUE", "PREDIQUE", "PRIAPIQUE", "PROSAÏQUE", "PROTÉIQUE", "PROTIQUE", "PRUSSIQUE"]},
  {"label":"PS","words":["PSYCHIQUE"]},
  {"label":"PU","words":["PUBLIQUE", "PUDIQUE", "PUNIQUE", "PURIQUE"]},
  {"label":"PY","words":["PYCNIQUE", "PYLORIQUE", "PYRÉTIQUE", "PYRRHIQUE", "PYRUVIQUE", "PYTHIQUE"]},
  {"label":"QU","words":["QUADRIQUE", "QUANTIQUE", "QUARTIQUE", "QUOIQUE"]},
  {"label":"RA","words":["RABIQUE", "RACÉMIQUE", "RADIQUE", "RAPPLIQUE"]},
  {"label":"RE","words":["REBIQUE", "RELIQUE", "REPIQUE", "RÉPLIQUE", "RÉSINIQUE", "RÉTIQUE"]},
  {"label":"RH","words":["RHÉTIQUE", "RHOMBIQUE"]},
  {"label":"RO","words":["ROBOTIQUE", "ROMAÏQUE", "ROMÉIQUE"]},
  {"label":"RU","words":["RUBRIQUE", "RUNIQUE", "RUSTIQUE"]},
  {"label":"RY","words":["RYTHMIQUE"]},
  {"label":"SA","words":["SADIQUE", "SALIQUE", "SALTIQUE", "SAPHIQUE", "SATANIQUE", "SATIRIQUE", "SATYRIQUE"]},
  {"label":"SC","words":["SCALDIQUE", "SCÉNIQUE", "SCEPTIQUE", "SCIATIQUE", "SCYTHIQUE"]},
  {"label":"SE","words":["SÉISMIQUE", "SÉLÉNIQUE", "SÉMIQUE", "SÉMITIQUE", "SEPTIQUE", "SÉRIQUE"]},
  {"label":"SI","words":["SIALIQUE", "SIDATIQUE", "SILICIQUE", "SILIQUE", "SISMIQUE"]},
  {"label":"SM","words":["SMECTIQUE"]},
  {"label":"SO","words":["SODIQUE", "SOMATIQUE", "SONIQUE", "SORBIQUE"]},
  {"label":"SP","words":["SPASTIQUE", "SPATHIQUE", "SPHÉRIQUE", "SPLÉNIQUE"]},
  {"label":"ST","words":["STANNIQUE", "STATIQUE", "STÉARIQUE", "STEPPIQUE", "STÉRIQUE", "STHÉNIQUE", "STOÏQUE", "STRABIQUE", "STYLIQUE", "STYPTIQUE"]},
  {"label":"SU","words":["SUPPLIQUE", "SURMOÏQUE", "SURPIQUE"]},
  {"label":"SY","words":["SYNDIQUE", "SYNODIQUE"]},
  {"label":"TA","words":["TABAGIQUE", "TABÉTIQUE", "TACTIQUE", "TANIQUE", "TANNIQUE", "TANTRIQUE", "TARTRIQUE"]},
  {"label":"TC","words":["TCHADIQUE"]},
  {"label":"TE","words":["TECHNIQUE", "TÉRÉBIQUE", "TÉTANIQUE"]},
  {"label":"TH","words":["THÉBAÏQUE", "THÉORIQUE", "THERMIQUE", "THÉTIQUE", "THIONIQUE", "THYMIQUE"]},
  {"label":"TI","words":["TIQUE", "TITANIQUE"]},
  {"label":"TO","words":["TONÉTIQUE", "TONIQUE", "TOPIQUE", "TORIQUE", "TOTÉMIQUE", "TOURNIQUE", "TOXÉMIQUE", "TOXIQUE"]},
  {"label":"TR","words":["TRAFIQUE", "TRAGIQUE", "TRIADIQUE", "TRIASIQUE", "TRIQUE", "TRISMIQUE", "TROPHIQUE", "TROPIQUE"]},
  {"label":"TU","words":["TUNIQUÉ", "TURCIQUE"]},
  {"label":"TY","words":["TYPHIQUE", "TYPIQUE"]},
  {"label":"UN","words":["UNIQUE"]},
  {"label":"UR","words":["URANIQUE", "URÉIQUE", "URÉMIQUE", "URIQUE", "URONIQUE"]},
  {"label":"UT","words":["UTOPIQUE"]},
  {"label":"VA","words":["VALÉRIQUE", "VANADIQUE"]},
  {"label":"VE","words":["VÉDIQUE", "VEHMIQUE", "VÉLIQUE", "VÉRIDIQUE", "VÉRONIQUE", "VÉSANIQUE"]},
  {"label":"VI","words":["VIATIQUE", "VINIQUE", "VINYLIQUE"]},
  {"label":"VO","words":["VOCALIQUE", "VOLÉMIQUE", "VOLTAÏQUE", "VOLUMIQUE", "VOMIQUE"]},
  {"label":"XA","words":["XANTHIQUE"]},
  {"label":"XE","words":["XÉRIQUE"]},
  {"label":"YO","words":["YOGIQUE"]},
  {"label":"YT","words":["YTTRIQUE"]},
  {"label":"ZE","words":["ZÉTÉTIQUE"]},
  {"label":"ZI","words":["ZINCIQUE", "ZIZIQUE"]},
  {"label":"ZU","words":["ZUTIQUE"]},
  {"label":"ZY","words":["ZYMOTIQUE"]},
];
